package ujn.school.cn.dao.content;

import java.util.List;

import ujn.school.cn.model.content.Content;
import ujn.school.cn.model.content.ContentWithBLOBs;

public interface ContentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujn_content
     *
     * @mbg.generated Mon Mar 27 13:11:59 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujn_content
     *
     * @mbg.generated Mon Mar 27 13:11:59 CST 2017
     */
    int insert(ContentWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujn_content
     *
     * @mbg.generated Mon Mar 27 13:11:59 CST 2017
     */
    int insertSelective(ContentWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujn_content
     *
     * @mbg.generated Mon Mar 27 13:11:59 CST 2017
     */
    ContentWithBLOBs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujn_content
     *
     * @mbg.generated Mon Mar 27 13:11:59 CST 2017
     */
    int updateByPrimaryKeySelective(ContentWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujn_content
     *
     * @mbg.generated Mon Mar 27 13:11:59 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(ContentWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujn_content
     *
     * @mbg.generated Mon Mar 27 13:11:59 CST 2017
     */
    int updateByPrimaryKey(Content record);

	List<Content> queryContentList(Content content);

	List<Content> queryContentListByColumn(Content content);

	int recoverContent(int contentId);

	List<Content> queryContentRecycleList(Content content);

	void deleteContentByColumnId(String id);

	List<Content> queryAuditContentList(Content content);
}