package com.yuanyuansinian.model.oration;

public class Oration {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_oration.Id
     *
     * @mbg.generated Fri Mar 10 10:06:41 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_oration.hall
     *
     * @mbg.generated Fri Mar 10 10:06:41 CST 2017
     */
    private String hall;
    private String hall_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_oration.title
     *
     * @mbg.generated Fri Mar 10 10:06:41 CST 2017
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_oration.keywords
     *
     * @mbg.generated Fri Mar 10 10:06:41 CST 2017
     */
    private String keywords;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_oration.tags
     *
     * @mbg.generated Fri Mar 10 10:06:41 CST 2017
     */
    private String tags;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_oration.no_order
     *
     * @mbg.generated Fri Mar 10 10:06:41 CST 2017
     */
    private Integer no_order;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_oration.create_date
     *
     * @mbg.generated Fri Mar 10 10:06:41 CST 2017
     */
    private String create_date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_oration.create_user
     *
     * @mbg.generated Fri Mar 10 10:06:41 CST 2017
     */
    private String create_user;
    private String create_user_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_oration.open_type
     *
     * @mbg.generated Fri Mar 10 10:06:41 CST 2017
     */
    private String open_type;
    private String open_type_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_oration.content
     *
     * @mbg.generated Fri Mar 10 10:06:41 CST 2017
     */
    private String content;
    
    private String imgs;

    public String getImgs() {
		return imgs;
	}

	public void setImgs(String imgs) {
		this.imgs = imgs;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_oration.Id
     *
     * @return the value of ujn_oration.Id
     *
     * @mbg.generated Fri Mar 10 10:06:41 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_oration.Id
     *
     * @param id the value for ujn_oration.Id
     *
     * @mbg.generated Fri Mar 10 10:06:41 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_oration.hall
     *
     * @return the value of ujn_oration.hall
     *
     * @mbg.generated Fri Mar 10 10:06:41 CST 2017
     */
    public String getHall() {
        return hall;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_oration.hall
     *
     * @param hall the value for ujn_oration.hall
     *
     * @mbg.generated Fri Mar 10 10:06:41 CST 2017
     */
    public void setHall(String hall) {
        this.hall = hall == null ? null : hall.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_oration.title
     *
     * @return the value of ujn_oration.title
     *
     * @mbg.generated Fri Mar 10 10:06:41 CST 2017
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_oration.title
     *
     * @param title the value for ujn_oration.title
     *
     * @mbg.generated Fri Mar 10 10:06:41 CST 2017
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_oration.keywords
     *
     * @return the value of ujn_oration.keywords
     *
     * @mbg.generated Fri Mar 10 10:06:41 CST 2017
     */
    public String getKeywords() {
        return keywords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_oration.keywords
     *
     * @param keywords the value for ujn_oration.keywords
     *
     * @mbg.generated Fri Mar 10 10:06:41 CST 2017
     */
    public void setKeywords(String keywords) {
        this.keywords = keywords == null ? null : keywords.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_oration.tags
     *
     * @return the value of ujn_oration.tags
     *
     * @mbg.generated Fri Mar 10 10:06:41 CST 2017
     */
    public String getTags() {
        return tags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_oration.tags
     *
     * @param tags the value for ujn_oration.tags
     *
     * @mbg.generated Fri Mar 10 10:06:41 CST 2017
     */
    public void setTags(String tags) {
        this.tags = tags == null ? null : tags.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_oration.no_order
     *
     * @return the value of ujn_oration.no_order
     *
     * @mbg.generated Fri Mar 10 10:06:41 CST 2017
     */
    public Integer getNo_order() {
        return no_order;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_oration.no_order
     *
     * @param no_order the value for ujn_oration.no_order
     *
     * @mbg.generated Fri Mar 10 10:06:41 CST 2017
     */
    public void setNo_order(Integer no_order) {
        this.no_order = no_order;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_oration.create_date
     *
     * @return the value of ujn_oration.create_date
     *
     * @mbg.generated Fri Mar 10 10:06:41 CST 2017
     */
    public String getCreate_date() {
        return create_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_oration.create_date
     *
     * @param create_date the value for ujn_oration.create_date
     *
     * @mbg.generated Fri Mar 10 10:06:41 CST 2017
     */
    public void setCreate_date(String create_date) {
        this.create_date = create_date == null ? null : create_date.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_oration.create_user
     *
     * @return the value of ujn_oration.create_user
     *
     * @mbg.generated Fri Mar 10 10:06:41 CST 2017
     */
    public String getCreate_user() {
        return create_user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_oration.create_user
     *
     * @param create_user the value for ujn_oration.create_user
     *
     * @mbg.generated Fri Mar 10 10:06:41 CST 2017
     */
    public void setCreate_user(String create_user) {
        this.create_user = create_user == null ? null : create_user.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_oration.open_type
     *
     * @return the value of ujn_oration.open_type
     *
     * @mbg.generated Fri Mar 10 10:06:41 CST 2017
     */
    public String getOpen_type() {
        return open_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_oration.open_type
     *
     * @param open_type the value for ujn_oration.open_type
     *
     * @mbg.generated Fri Mar 10 10:06:41 CST 2017
     */
    public void setOpen_type(String open_type) {
        this.open_type = open_type == null ? null : open_type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_oration.content
     *
     * @return the value of ujn_oration.content
     *
     * @mbg.generated Fri Mar 10 10:06:41 CST 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_oration.content
     *
     * @param content the value for ujn_oration.content
     *
     * @mbg.generated Fri Mar 10 10:06:41 CST 2017
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

	public String getHall_name() {
		return hall_name;
	}

	public void setHall_name(String hall_name) {
		this.hall_name = hall_name;
	}

	public String getCreate_user_name() {
		return create_user_name;
	}

	public void setCreate_user_name(String create_user_name) {
		this.create_user_name = create_user_name;
	}

	public String getOpen_type_name() {
		return open_type_name;
	}

	public void setOpen_type_name(String open_type_name) {
		this.open_type_name = open_type_name;
	}
}