package ujn.school.cn.model.file;

public class File {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_file.Id
     *
     * @mbg.generated Thu Aug 03 14:43:21 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_file.belong_id
     *
     * @mbg.generated Thu Aug 03 14:43:21 CST 2017
     */
    private String belong_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_file.file_type
     *
     * @mbg.generated Thu Aug 03 14:43:21 CST 2017
     */
    private String file_type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_file.file_name
     *
     * @mbg.generated Thu Aug 03 14:43:21 CST 2017
     */
    private String file_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_file.file_size
     *
     * @mbg.generated Thu Aug 03 14:43:21 CST 2017
     */
    private Integer file_size;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_file.file_path
     *
     * @mbg.generated Thu Aug 03 14:43:21 CST 2017
     */
    private String file_path;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_file.create_date
     *
     * @mbg.generated Thu Aug 03 14:43:21 CST 2017
     */
    private String create_date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_file.file_status
     *
     * @mbg.generated Thu Aug 03 14:43:21 CST 2017
     */
    private String file_status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_file.Id
     *
     * @return the value of ujn_file.Id
     *
     * @mbg.generated Thu Aug 03 14:43:21 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_file.Id
     *
     * @param id the value for ujn_file.Id
     *
     * @mbg.generated Thu Aug 03 14:43:21 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_file.belong_id
     *
     * @return the value of ujn_file.belong_id
     *
     * @mbg.generated Thu Aug 03 14:43:21 CST 2017
     */
    public String getBelong_id() {
        return belong_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_file.belong_id
     *
     * @param belong_id the value for ujn_file.belong_id
     *
     * @mbg.generated Thu Aug 03 14:43:21 CST 2017
     */
    public void setBelong_id(String belong_id) {
        this.belong_id = belong_id == null ? null : belong_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_file.file_type
     *
     * @return the value of ujn_file.file_type
     *
     * @mbg.generated Thu Aug 03 14:43:21 CST 2017
     */
    public String getFile_type() {
        return file_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_file.file_type
     *
     * @param file_type the value for ujn_file.file_type
     *
     * @mbg.generated Thu Aug 03 14:43:21 CST 2017
     */
    public void setFile_type(String file_type) {
        this.file_type = file_type == null ? null : file_type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_file.file_name
     *
     * @return the value of ujn_file.file_name
     *
     * @mbg.generated Thu Aug 03 14:43:21 CST 2017
     */
    public String getFile_name() {
        return file_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_file.file_name
     *
     * @param file_name the value for ujn_file.file_name
     *
     * @mbg.generated Thu Aug 03 14:43:21 CST 2017
     */
    public void setFile_name(String file_name) {
        this.file_name = file_name == null ? null : file_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_file.file_size
     *
     * @return the value of ujn_file.file_size
     *
     * @mbg.generated Thu Aug 03 14:43:21 CST 2017
     */
    public Integer getFile_size() {
        return file_size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_file.file_size
     *
     * @param file_size the value for ujn_file.file_size
     *
     * @mbg.generated Thu Aug 03 14:43:21 CST 2017
     */
    public void setFile_size(Integer file_size) {
        this.file_size = file_size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_file.file_path
     *
     * @return the value of ujn_file.file_path
     *
     * @mbg.generated Thu Aug 03 14:43:21 CST 2017
     */
    public String getFile_path() {
        return file_path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_file.file_path
     *
     * @param file_path the value for ujn_file.file_path
     *
     * @mbg.generated Thu Aug 03 14:43:21 CST 2017
     */
    public void setFile_path(String file_path) {
        this.file_path = file_path == null ? null : file_path.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_file.create_date
     *
     * @return the value of ujn_file.create_date
     *
     * @mbg.generated Thu Aug 03 14:43:21 CST 2017
     */
    public String getCreate_date() {
        return create_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_file.create_date
     *
     * @param create_date the value for ujn_file.create_date
     *
     * @mbg.generated Thu Aug 03 14:43:21 CST 2017
     */
    public void setCreate_date(String create_date) {
        this.create_date = create_date == null ? null : create_date.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_file.file_status
     *
     * @return the value of ujn_file.file_status
     *
     * @mbg.generated Thu Aug 03 14:43:21 CST 2017
     */
    public String getFile_status() {
        return file_status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_file.file_status
     *
     * @param file_status the value for ujn_file.file_status
     *
     * @mbg.generated Thu Aug 03 14:43:21 CST 2017
     */
    public void setFile_status(String file_status) {
        this.file_status = file_status == null ? null : file_status.trim();
    }
}