package com.suncity.dao.product;

import java.util.List;
import java.util.Map;

import com.suncity.model.product.Product;
import com.suncity.model.product.ProductWithBLOBs;

public interface ProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujn_product
     *
     * @mbg.generated Wed Mar 08 14:45:29 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujn_product
     *
     * @mbg.generated Wed Mar 08 14:45:29 CST 2017
     */
    int insert(ProductWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujn_product
     *
     * @mbg.generated Wed Mar 08 14:45:29 CST 2017
     */
    int insertSelective(ProductWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujn_product
     *
     * @mbg.generated Wed Mar 08 14:45:29 CST 2017
     */
    ProductWithBLOBs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujn_product
     *
     * @mbg.generated Wed Mar 08 14:45:29 CST 2017
     */
    int updateByPrimaryKeySelective(ProductWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujn_product
     *
     * @mbg.generated Wed Mar 08 14:45:29 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(ProductWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujn_product
     *
     * @mbg.generated Wed Mar 08 14:45:29 CST 2017
     */
    int updateByPrimaryKey(Product record);

	List<Product> queryProductList(Product product);

	List<Product> queryProductListByType(String type);

	int recoverProduct(int productId);

	List<Product> queryProductRecycleList(Product product);

	void uploadImg(Product product);

	List<Product> queryProductListByIds(Map<String, Object> map);

}