package com.yuanyuansinian.model.column;

public class ColumnWithBLOBs extends Column {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_column.content
     *
     * @mbg.generated Mon Feb 06 11:15:53 CST 2017
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_column.description
     *
     * @mbg.generated Mon Feb 06 11:15:53 CST 2017
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_column.content
     *
     * @return the value of ujn_column.content
     *
     * @mbg.generated Mon Feb 06 11:15:53 CST 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_column.content
     *
     * @param content the value for ujn_column.content
     *
     * @mbg.generated Mon Feb 06 11:15:53 CST 2017
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_column.description
     *
     * @return the value of ujn_column.description
     *
     * @mbg.generated Mon Feb 06 11:15:53 CST 2017
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_column.description
     *
     * @param description the value for ujn_column.description
     *
     * @mbg.generated Mon Feb 06 11:15:53 CST 2017
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}