package com.yuanyuansinian.model.column;

public class Column {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_column.id
     *
     * @mbg.generated Mon Feb 06 11:15:53 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_column.name
     *
     * @mbg.generated Mon Feb 06 11:15:53 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_column.folder_name
     *
     * @mbg.generated Mon Feb 06 11:15:53 CST 2017
     */
    private String folder_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_column.file_name
     *
     * @mbg.generated Mon Feb 06 11:15:53 CST 2017
     */
    private String file_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_column.big_class
     *
     * @mbg.generated Mon Feb 06 11:15:53 CST 2017
     */
    private Integer big_class;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_column.module
     *
     * @mbg.generated Mon Feb 06 11:15:53 CST 2017
     */
    private Integer module;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_column.no_order
     *
     * @mbg.generated Mon Feb 06 11:15:53 CST 2017
     */
    private Integer no_order;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_column.if_in
     *
     * @mbg.generated Mon Feb 06 11:15:53 CST 2017
     */
    private Integer if_in;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_column.nav
     *
     * @mbg.generated Mon Feb 06 11:15:53 CST 2017
     */
    private Integer nav;
    private String nav_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_column.ctitle
     *
     * @mbg.generated Mon Feb 06 11:15:53 CST 2017
     */
    private String ctitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_column.keywords
     *
     * @mbg.generated Mon Feb 06 11:15:53 CST 2017
     */
    private String keywords;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_column.list_order
     *
     * @mbg.generated Mon Feb 06 11:15:53 CST 2017
     */
    private Integer list_order;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_column.new_windows
     *
     * @mbg.generated Mon Feb 06 11:15:53 CST 2017
     */
    private String new_windows;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_column.class_type
     *
     * @mbg.generated Mon Feb 06 11:15:53 CST 2017
     */
    private Integer class_type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_column.out_url
     *
     * @mbg.generated Mon Feb 06 11:15:53 CST 2017
     */
    private String out_url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_column.index_num
     *
     * @mbg.generated Mon Feb 06 11:15:53 CST 2017
     */
    private Integer index_num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_column.access
     *
     * @mbg.generated Mon Feb 06 11:15:53 CST 2017
     */
    private Integer access;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_column.index_img
     *
     * @mbg.generated Mon Feb 06 11:15:53 CST 2017
     */
    private String index_img;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_column.column_img
     *
     * @mbg.generated Mon Feb 06 11:15:53 CST 2017
     */
    private String column_img;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_column.is_show
     *
     * @mbg.generated Mon Feb 06 11:15:53 CST 2017
     */
    private Integer is_show;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_column.lang
     *
     * @mbg.generated Mon Feb 06 11:15:53 CST 2017
     */
    private String lang;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_column.name_mark
     *
     * @mbg.generated Mon Feb 06 11:15:53 CST 2017
     */
    private String name_mark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_column.rele_class
     *
     * @mbg.generated Mon Feb 06 11:15:53 CST 2017
     */
    private Integer rele_class;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_column.display
     *
     * @mbg.generated Mon Feb 06 11:15:53 CST 2017
     */
    private Integer display;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_column.add_class
     *
     * @mbg.generated Mon Feb 06 11:15:53 CST 2017
     */
    private String add_class;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_column.id
     *
     * @return the value of ujn_column.id
     *
     * @mbg.generated Mon Feb 06 11:15:53 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_column.id
     *
     * @param id the value for ujn_column.id
     *
     * @mbg.generated Mon Feb 06 11:15:53 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_column.name
     *
     * @return the value of ujn_column.name
     *
     * @mbg.generated Mon Feb 06 11:15:53 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_column.name
     *
     * @param name the value for ujn_column.name
     *
     * @mbg.generated Mon Feb 06 11:15:53 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_column.folder_name
     *
     * @return the value of ujn_column.folder_name
     *
     * @mbg.generated Mon Feb 06 11:15:53 CST 2017
     */
    public String getFolder_name() {
        return folder_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_column.folder_name
     *
     * @param folder_name the value for ujn_column.folder_name
     *
     * @mbg.generated Mon Feb 06 11:15:53 CST 2017
     */
    public void setFolder_name(String folder_name) {
        this.folder_name = folder_name == null ? null : folder_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_column.file_name
     *
     * @return the value of ujn_column.file_name
     *
     * @mbg.generated Mon Feb 06 11:15:53 CST 2017
     */
    public String getFile_name() {
        return file_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_column.file_name
     *
     * @param file_name the value for ujn_column.file_name
     *
     * @mbg.generated Mon Feb 06 11:15:53 CST 2017
     */
    public void setFile_name(String file_name) {
        this.file_name = file_name == null ? null : file_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_column.big_class
     *
     * @return the value of ujn_column.big_class
     *
     * @mbg.generated Mon Feb 06 11:15:53 CST 2017
     */
    public Integer getBig_class() {
        return big_class;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_column.big_class
     *
     * @param big_class the value for ujn_column.big_class
     *
     * @mbg.generated Mon Feb 06 11:15:53 CST 2017
     */
    public void setBig_class(Integer big_class) {
        this.big_class = big_class;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_column.module
     *
     * @return the value of ujn_column.module
     *
     * @mbg.generated Mon Feb 06 11:15:53 CST 2017
     */
    public Integer getModule() {
        return module;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_column.module
     *
     * @param module the value for ujn_column.module
     *
     * @mbg.generated Mon Feb 06 11:15:53 CST 2017
     */
    public void setModule(Integer module) {
        this.module = module;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_column.no_order
     *
     * @return the value of ujn_column.no_order
     *
     * @mbg.generated Mon Feb 06 11:15:53 CST 2017
     */
    public Integer getNo_order() {
        return no_order;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_column.no_order
     *
     * @param no_order the value for ujn_column.no_order
     *
     * @mbg.generated Mon Feb 06 11:15:53 CST 2017
     */
    public void setNo_order(Integer no_order) {
        this.no_order = no_order;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_column.if_in
     *
     * @return the value of ujn_column.if_in
     *
     * @mbg.generated Mon Feb 06 11:15:53 CST 2017
     */
    public Integer getIf_in() {
        return if_in;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_column.if_in
     *
     * @param if_in the value for ujn_column.if_in
     *
     * @mbg.generated Mon Feb 06 11:15:53 CST 2017
     */
    public void setIf_in(Integer if_in) {
        this.if_in = if_in;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_column.nav
     *
     * @return the value of ujn_column.nav
     *
     * @mbg.generated Mon Feb 06 11:15:53 CST 2017
     */
    public Integer getNav() {
        return nav;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_column.nav
     *
     * @param nav the value for ujn_column.nav
     *
     * @mbg.generated Mon Feb 06 11:15:53 CST 2017
     */
    public void setNav(Integer nav) {
        this.nav = nav;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_column.ctitle
     *
     * @return the value of ujn_column.ctitle
     *
     * @mbg.generated Mon Feb 06 11:15:53 CST 2017
     */
    public String getCtitle() {
        return ctitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_column.ctitle
     *
     * @param ctitle the value for ujn_column.ctitle
     *
     * @mbg.generated Mon Feb 06 11:15:53 CST 2017
     */
    public void setCtitle(String ctitle) {
        this.ctitle = ctitle == null ? null : ctitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_column.keywords
     *
     * @return the value of ujn_column.keywords
     *
     * @mbg.generated Mon Feb 06 11:15:53 CST 2017
     */
    public String getKeywords() {
        return keywords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_column.keywords
     *
     * @param keywords the value for ujn_column.keywords
     *
     * @mbg.generated Mon Feb 06 11:15:53 CST 2017
     */
    public void setKeywords(String keywords) {
        this.keywords = keywords == null ? null : keywords.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_column.list_order
     *
     * @return the value of ujn_column.list_order
     *
     * @mbg.generated Mon Feb 06 11:15:53 CST 2017
     */
    public Integer getList_order() {
        return list_order;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_column.list_order
     *
     * @param list_order the value for ujn_column.list_order
     *
     * @mbg.generated Mon Feb 06 11:15:53 CST 2017
     */
    public void setList_order(Integer list_order) {
        this.list_order = list_order;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_column.new_windows
     *
     * @return the value of ujn_column.new_windows
     *
     * @mbg.generated Mon Feb 06 11:15:53 CST 2017
     */
    public String getNew_windows() {
        return new_windows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_column.new_windows
     *
     * @param new_windows the value for ujn_column.new_windows
     *
     * @mbg.generated Mon Feb 06 11:15:53 CST 2017
     */
    public void setNew_windows(String new_windows) {
        this.new_windows = new_windows == null ? null : new_windows.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_column.class_type
     *
     * @return the value of ujn_column.class_type
     *
     * @mbg.generated Mon Feb 06 11:15:53 CST 2017
     */
    public Integer getClass_type() {
        return class_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_column.class_type
     *
     * @param class_type the value for ujn_column.class_type
     *
     * @mbg.generated Mon Feb 06 11:15:53 CST 2017
     */
    public void setClass_type(Integer class_type) {
        this.class_type = class_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_column.out_url
     *
     * @return the value of ujn_column.out_url
     *
     * @mbg.generated Mon Feb 06 11:15:53 CST 2017
     */
    public String getOut_url() {
        return out_url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_column.out_url
     *
     * @param out_url the value for ujn_column.out_url
     *
     * @mbg.generated Mon Feb 06 11:15:53 CST 2017
     */
    public void setOut_url(String out_url) {
        this.out_url = out_url == null ? null : out_url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_column.index_num
     *
     * @return the value of ujn_column.index_num
     *
     * @mbg.generated Mon Feb 06 11:15:53 CST 2017
     */
    public Integer getIndex_num() {
        return index_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_column.index_num
     *
     * @param index_num the value for ujn_column.index_num
     *
     * @mbg.generated Mon Feb 06 11:15:53 CST 2017
     */
    public void setIndex_num(Integer index_num) {
        this.index_num = index_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_column.access
     *
     * @return the value of ujn_column.access
     *
     * @mbg.generated Mon Feb 06 11:15:53 CST 2017
     */
    public Integer getAccess() {
        return access;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_column.access
     *
     * @param access the value for ujn_column.access
     *
     * @mbg.generated Mon Feb 06 11:15:53 CST 2017
     */
    public void setAccess(Integer access) {
        this.access = access;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_column.index_img
     *
     * @return the value of ujn_column.index_img
     *
     * @mbg.generated Mon Feb 06 11:15:53 CST 2017
     */
    public String getIndex_img() {
        return index_img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_column.index_img
     *
     * @param index_img the value for ujn_column.index_img
     *
     * @mbg.generated Mon Feb 06 11:15:53 CST 2017
     */
    public void setIndex_img(String index_img) {
        this.index_img = index_img == null ? null : index_img.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_column.column_img
     *
     * @return the value of ujn_column.column_img
     *
     * @mbg.generated Mon Feb 06 11:15:53 CST 2017
     */
    public String getColumn_img() {
        return column_img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_column.column_img
     *
     * @param column_img the value for ujn_column.column_img
     *
     * @mbg.generated Mon Feb 06 11:15:53 CST 2017
     */
    public void setColumn_img(String column_img) {
        this.column_img = column_img == null ? null : column_img.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_column.is_show
     *
     * @return the value of ujn_column.is_show
     *
     * @mbg.generated Mon Feb 06 11:15:53 CST 2017
     */
    public Integer getIs_show() {
        return is_show;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_column.is_show
     *
     * @param is_show the value for ujn_column.is_show
     *
     * @mbg.generated Mon Feb 06 11:15:53 CST 2017
     */
    public void setIs_show(Integer is_show) {
        this.is_show = is_show;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_column.lang
     *
     * @return the value of ujn_column.lang
     *
     * @mbg.generated Mon Feb 06 11:15:53 CST 2017
     */
    public String getLang() {
        return lang;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_column.lang
     *
     * @param lang the value for ujn_column.lang
     *
     * @mbg.generated Mon Feb 06 11:15:53 CST 2017
     */
    public void setLang(String lang) {
        this.lang = lang == null ? null : lang.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_column.name_mark
     *
     * @return the value of ujn_column.name_mark
     *
     * @mbg.generated Mon Feb 06 11:15:53 CST 2017
     */
    public String getName_mark() {
        return name_mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_column.name_mark
     *
     * @param name_mark the value for ujn_column.name_mark
     *
     * @mbg.generated Mon Feb 06 11:15:53 CST 2017
     */
    public void setName_mark(String name_mark) {
        this.name_mark = name_mark == null ? null : name_mark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_column.rele_class
     *
     * @return the value of ujn_column.rele_class
     *
     * @mbg.generated Mon Feb 06 11:15:53 CST 2017
     */
    public Integer getRele_class() {
        return rele_class;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_column.rele_class
     *
     * @param rele_class the value for ujn_column.rele_class
     *
     * @mbg.generated Mon Feb 06 11:15:53 CST 2017
     */
    public void setRele_class(Integer rele_class) {
        this.rele_class = rele_class;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_column.display
     *
     * @return the value of ujn_column.display
     *
     * @mbg.generated Mon Feb 06 11:15:53 CST 2017
     */
    public Integer getDisplay() {
        return display;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_column.display
     *
     * @param display the value for ujn_column.display
     *
     * @mbg.generated Mon Feb 06 11:15:53 CST 2017
     */
    public void setDisplay(Integer display) {
        this.display = display;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_column.add_class
     *
     * @return the value of ujn_column.add_class
     *
     * @mbg.generated Mon Feb 06 11:15:53 CST 2017
     */
    public String getAdd_class() {
        return add_class;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_column.add_class
     *
     * @param add_class the value for ujn_column.add_class
     *
     * @mbg.generated Mon Feb 06 11:15:53 CST 2017
     */
    public void setAdd_class(String add_class) {
        this.add_class = add_class == null ? null : add_class.trim();
    }

	public String getNav_name() {
		return nav_name;
	}

	public void setNav_name(String nav_name) {
		this.nav_name = nav_name;
	}
}