package com.yuanyuansinian.model.hall;

public class HallDouble {
	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ujn_hall_double.Id
	 *
	 * @mbg.generated Fri May 05 15:28:30 CST 2017
	 */
	private Integer id;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ujn_hall_double.title
	 *
	 * @mbg.generated Fri May 05 15:28:30 CST 2017
	 */
	private String title;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ujn_hall_double.description
	 *
	 * @mbg.generated Fri May 05 15:28:30 CST 2017
	 */
	private String description;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ujn_hall_double.imgs
	 *
	 * @mbg.generated Fri May 05 15:28:30 CST 2017
	 */
	private String imgs;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ujn_hall_double.name
	 *
	 * @mbg.generated Fri May 05 15:28:30 CST 2017
	 */
	private String name;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ujn_hall_double.alias
	 *
	 * @mbg.generated Fri May 05 15:28:30 CST 2017
	 */
	private String alias;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ujn_hall_double.sex
	 *
	 * @mbg.generated Fri May 05 15:28:30 CST 2017
	 */
	private String sex;
	private String sex_name;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ujn_hall_double.nationality
	 *
	 * @mbg.generated Fri May 05 15:28:30 CST 2017
	 */
	private String nationality;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ujn_hall_double.nation
	 *
	 * @mbg.generated Fri May 05 15:28:30 CST 2017
	 */
	private String nation;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ujn_hall_double.address
	 *
	 * @mbg.generated Fri May 05 15:28:30 CST 2017
	 */
	private String address;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ujn_hall_double.belief
	 *
	 * @mbg.generated Fri May 05 15:28:30 CST 2017
	 */
	private String belief;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ujn_hall_double.birthplace
	 *
	 * @mbg.generated Fri May 05 15:28:30 CST 2017
	 */
	private String birthplace;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ujn_hall_double.native_place
	 *
	 * @mbg.generated Fri May 05 15:28:30 CST 2017
	 */
	private String native_place;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ujn_hall_double.open_type
	 *
	 * @mbg.generated Fri May 05 15:28:30 CST 2017
	 */
	private String open_type;
	private String open_type_name;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ujn_hall_double.status
	 *
	 * @mbg.generated Fri May 05 15:28:30 CST 2017
	 */
	private String status;
	private String status_name;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ujn_hall_double.create_date
	 *
	 * @mbg.generated Fri May 05 15:28:30 CST 2017
	 */
	private String create_date;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ujn_hall_double.validity
	 *
	 * @mbg.generated Fri May 05 15:28:30 CST 2017
	 */
	private String validity;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ujn_hall_double.create_user
	 *
	 * @mbg.generated Fri May 05 15:28:30 CST 2017
	 */
	private String create_user;
	private String create_user_name;
	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ujn_hall_double.hall_type
	 *
	 * @mbg.generated Fri May 05 15:28:30 CST 2017
	 */
	private String hall_type;
	private String hall_type_name;
	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ujn_hall_double.alive_date
	 *
	 * @mbg.generated Fri May 05 15:28:30 CST 2017
	 */
	private String alive_date;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ujn_hall_double.name2
	 *
	 * @mbg.generated Fri May 05 15:28:30 CST 2017
	 */
	private String name2;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ujn_hall_double.alias2
	 *
	 * @mbg.generated Fri May 05 15:28:30 CST 2017
	 */
	private String alias2;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ujn_hall_double.sex2
	 *
	 * @mbg.generated Fri May 05 15:28:30 CST 2017
	 */
	private String sex2;
	private String sex2_name;

	public String getSex_name() {
		return sex_name;
	}

	public void setSex_name(String sex_name) {
		this.sex_name = sex_name;
	}

	public String getOpen_type_name() {
		return open_type_name;
	}

	public void setOpen_type_name(String open_type_name) {
		this.open_type_name = open_type_name;
	}

	public String getStatus_name() {
		return status_name;
	}

	public void setStatus_name(String status_name) {
		this.status_name = status_name;
	}

	public String getCreate_user_name() {
		return create_user_name;
	}

	public void setCreate_user_name(String create_user_name) {
		this.create_user_name = create_user_name;
	}

	public String getHall_type_name() {
		return hall_type_name;
	}

	public void setHall_type_name(String hall_type_name) {
		this.hall_type_name = hall_type_name;
	}

	public String getSex2_name() {
		return sex2_name;
	}

	public void setSex2_name(String sex2_name) {
		this.sex2_name = sex2_name;
	}

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ujn_hall_double.nationality2
	 *
	 * @mbg.generated Fri May 05 15:28:30 CST 2017
	 */
	private String nationality2;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ujn_hall_double.nation2
	 *
	 * @mbg.generated Fri May 05 15:28:30 CST 2017
	 */
	private String nation2;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ujn_hall_double.address2
	 *
	 * @mbg.generated Fri May 05 15:28:30 CST 2017
	 */
	private String address2;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ujn_hall_double.belief2
	 *
	 * @mbg.generated Fri May 05 15:28:30 CST 2017
	 */
	private String belief2;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ujn_hall_double.birthplace2
	 *
	 * @mbg.generated Fri May 05 15:28:30 CST 2017
	 */
	private String birthplace2;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ujn_hall_double.native_place2
	 *
	 * @mbg.generated Fri May 05 15:28:30 CST 2017
	 */
	private String native_place2;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ujn_hall_double.alive_date2
	 *
	 * @mbg.generated Fri May 05 15:28:30 CST 2017
	 */
	private String alive_date2;

	// 生效
	private String zodiac;
	// 生日
	private String birthday;
	// 去世时间
	private String death_date;

	// 生效
	private String zodiac2;
	// 生日
	private String birthday2;
	// 去世时间
	private String death_date2;

	// 离世天数
	private int days;

	// 头像
	private String img_head;
	// 头像
	private String img_head2;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ujn_hall_double.Id
	 *
	 * @return the value of ujn_hall_double.Id
	 *
	 * @mbg.generated Fri May 05 15:28:30 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ujn_hall_double.Id
	 *
	 * @param id
	 *            the value for ujn_hall_double.Id
	 *
	 * @mbg.generated Fri May 05 15:28:30 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ujn_hall_double.title
	 *
	 * @return the value of ujn_hall_double.title
	 *
	 * @mbg.generated Fri May 05 15:28:30 CST 2017
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ujn_hall_double.title
	 *
	 * @param title
	 *            the value for ujn_hall_double.title
	 *
	 * @mbg.generated Fri May 05 15:28:30 CST 2017
	 */
	public void setTitle(String title) {
		this.title = title == null ? null : title.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ujn_hall_double.description
	 *
	 * @return the value of ujn_hall_double.description
	 *
	 * @mbg.generated Fri May 05 15:28:30 CST 2017
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ujn_hall_double.description
	 *
	 * @param description
	 *            the value for ujn_hall_double.description
	 *
	 * @mbg.generated Fri May 05 15:28:30 CST 2017
	 */
	public void setDescription(String description) {
		this.description = description == null ? null : description.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ujn_hall_double.imgs
	 *
	 * @return the value of ujn_hall_double.imgs
	 *
	 * @mbg.generated Fri May 05 15:28:30 CST 2017
	 */
	public String getImgs() {
		return imgs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ujn_hall_double.imgs
	 *
	 * @param imgs
	 *            the value for ujn_hall_double.imgs
	 *
	 * @mbg.generated Fri May 05 15:28:30 CST 2017
	 */
	public void setImgs(String imgs) {
		this.imgs = imgs == null ? null : imgs.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ujn_hall_double.name
	 *
	 * @return the value of ujn_hall_double.name
	 *
	 * @mbg.generated Fri May 05 15:28:30 CST 2017
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ujn_hall_double.name
	 *
	 * @param name
	 *            the value for ujn_hall_double.name
	 *
	 * @mbg.generated Fri May 05 15:28:30 CST 2017
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ujn_hall_double.alias
	 *
	 * @return the value of ujn_hall_double.alias
	 *
	 * @mbg.generated Fri May 05 15:28:30 CST 2017
	 */
	public String getAlias() {
		return alias;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ujn_hall_double.alias
	 *
	 * @param alias
	 *            the value for ujn_hall_double.alias
	 *
	 * @mbg.generated Fri May 05 15:28:30 CST 2017
	 */
	public void setAlias(String alias) {
		this.alias = alias == null ? null : alias.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ujn_hall_double.sex
	 *
	 * @return the value of ujn_hall_double.sex
	 *
	 * @mbg.generated Fri May 05 15:28:30 CST 2017
	 */
	public String getSex() {
		return sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ujn_hall_double.sex
	 *
	 * @param sex
	 *            the value for ujn_hall_double.sex
	 *
	 * @mbg.generated Fri May 05 15:28:30 CST 2017
	 */
	public void setSex(String sex) {
		this.sex = sex == null ? null : sex.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ujn_hall_double.nationality
	 *
	 * @return the value of ujn_hall_double.nationality
	 *
	 * @mbg.generated Fri May 05 15:28:30 CST 2017
	 */
	public String getNationality() {
		return nationality;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ujn_hall_double.nationality
	 *
	 * @param nationality
	 *            the value for ujn_hall_double.nationality
	 *
	 * @mbg.generated Fri May 05 15:28:30 CST 2017
	 */
	public void setNationality(String nationality) {
		this.nationality = nationality == null ? null : nationality.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ujn_hall_double.nation
	 *
	 * @return the value of ujn_hall_double.nation
	 *
	 * @mbg.generated Fri May 05 15:28:30 CST 2017
	 */
	public String getNation() {
		return nation;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ujn_hall_double.nation
	 *
	 * @param nation
	 *            the value for ujn_hall_double.nation
	 *
	 * @mbg.generated Fri May 05 15:28:30 CST 2017
	 */
	public void setNation(String nation) {
		this.nation = nation == null ? null : nation.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ujn_hall_double.address
	 *
	 * @return the value of ujn_hall_double.address
	 *
	 * @mbg.generated Fri May 05 15:28:30 CST 2017
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ujn_hall_double.address
	 *
	 * @param address
	 *            the value for ujn_hall_double.address
	 *
	 * @mbg.generated Fri May 05 15:28:30 CST 2017
	 */
	public void setAddress(String address) {
		this.address = address == null ? null : address.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ujn_hall_double.belief
	 *
	 * @return the value of ujn_hall_double.belief
	 *
	 * @mbg.generated Fri May 05 15:28:30 CST 2017
	 */
	public String getBelief() {
		return belief;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ujn_hall_double.belief
	 *
	 * @param belief
	 *            the value for ujn_hall_double.belief
	 *
	 * @mbg.generated Fri May 05 15:28:30 CST 2017
	 */
	public void setBelief(String belief) {
		this.belief = belief == null ? null : belief.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ujn_hall_double.birthplace
	 *
	 * @return the value of ujn_hall_double.birthplace
	 *
	 * @mbg.generated Fri May 05 15:28:30 CST 2017
	 */
	public String getBirthplace() {
		return birthplace;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ujn_hall_double.birthplace
	 *
	 * @param birthplace
	 *            the value for ujn_hall_double.birthplace
	 *
	 * @mbg.generated Fri May 05 15:28:30 CST 2017
	 */
	public void setBirthplace(String birthplace) {
		this.birthplace = birthplace == null ? null : birthplace.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ujn_hall_double.native_place
	 *
	 * @return the value of ujn_hall_double.native_place
	 *
	 * @mbg.generated Fri May 05 15:28:30 CST 2017
	 */
	public String getNative_place() {
		return native_place;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ujn_hall_double.native_place
	 *
	 * @param native_place
	 *            the value for ujn_hall_double.native_place
	 *
	 * @mbg.generated Fri May 05 15:28:30 CST 2017
	 */
	public void setNative_place(String native_place) {
		this.native_place = native_place == null ? null : native_place.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ujn_hall_double.open_type
	 *
	 * @return the value of ujn_hall_double.open_type
	 *
	 * @mbg.generated Fri May 05 15:28:30 CST 2017
	 */
	public String getOpen_type() {
		return open_type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ujn_hall_double.open_type
	 *
	 * @param open_type
	 *            the value for ujn_hall_double.open_type
	 *
	 * @mbg.generated Fri May 05 15:28:30 CST 2017
	 */
	public void setOpen_type(String open_type) {
		this.open_type = open_type == null ? null : open_type.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ujn_hall_double.status
	 *
	 * @return the value of ujn_hall_double.status
	 *
	 * @mbg.generated Fri May 05 15:28:30 CST 2017
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ujn_hall_double.status
	 *
	 * @param status
	 *            the value for ujn_hall_double.status
	 *
	 * @mbg.generated Fri May 05 15:28:30 CST 2017
	 */
	public void setStatus(String status) {
		this.status = status == null ? null : status.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ujn_hall_double.create_date
	 *
	 * @return the value of ujn_hall_double.create_date
	 *
	 * @mbg.generated Fri May 05 15:28:30 CST 2017
	 */
	public String getCreate_date() {
		return create_date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ujn_hall_double.create_date
	 *
	 * @param create_date
	 *            the value for ujn_hall_double.create_date
	 *
	 * @mbg.generated Fri May 05 15:28:30 CST 2017
	 */
	public void setCreate_date(String create_date) {
		this.create_date = create_date == null ? null : create_date.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ujn_hall_double.validity
	 *
	 * @return the value of ujn_hall_double.validity
	 *
	 * @mbg.generated Fri May 05 15:28:30 CST 2017
	 */
	public String getValidity() {
		return validity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ujn_hall_double.validity
	 *
	 * @param validity
	 *            the value for ujn_hall_double.validity
	 *
	 * @mbg.generated Fri May 05 15:28:30 CST 2017
	 */
	public void setValidity(String validity) {
		this.validity = validity == null ? null : validity.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ujn_hall_double.create_user
	 *
	 * @return the value of ujn_hall_double.create_user
	 *
	 * @mbg.generated Fri May 05 15:28:30 CST 2017
	 */
	public String getCreate_user() {
		return create_user;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ujn_hall_double.create_user
	 *
	 * @param create_user
	 *            the value for ujn_hall_double.create_user
	 *
	 * @mbg.generated Fri May 05 15:28:30 CST 2017
	 */
	public void setCreate_user(String create_user) {
		this.create_user = create_user == null ? null : create_user.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ujn_hall_double.hall_type
	 *
	 * @return the value of ujn_hall_double.hall_type
	 *
	 * @mbg.generated Fri May 05 15:28:30 CST 2017
	 */
	public String getHall_type() {
		return hall_type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ujn_hall_double.hall_type
	 *
	 * @param hall_type
	 *            the value for ujn_hall_double.hall_type
	 *
	 * @mbg.generated Fri May 05 15:28:30 CST 2017
	 */
	public void setHall_type(String hall_type) {
		this.hall_type = hall_type == null ? null : hall_type.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ujn_hall_double.alive_date
	 *
	 * @return the value of ujn_hall_double.alive_date
	 *
	 * @mbg.generated Fri May 05 15:28:30 CST 2017
	 */
	public String getAlive_date() {
		return alive_date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ujn_hall_double.alive_date
	 *
	 * @param alive_date
	 *            the value for ujn_hall_double.alive_date
	 *
	 * @mbg.generated Fri May 05 15:28:30 CST 2017
	 */
	public void setAlive_date(String alive_date) {
		this.alive_date = alive_date == null ? null : alive_date.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ujn_hall_double.name2
	 *
	 * @return the value of ujn_hall_double.name2
	 *
	 * @mbg.generated Fri May 05 15:28:30 CST 2017
	 */
	public String getName2() {
		return name2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ujn_hall_double.name2
	 *
	 * @param name2
	 *            the value for ujn_hall_double.name2
	 *
	 * @mbg.generated Fri May 05 15:28:30 CST 2017
	 */
	public void setName2(String name2) {
		this.name2 = name2 == null ? null : name2.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ujn_hall_double.alias2
	 *
	 * @return the value of ujn_hall_double.alias2
	 *
	 * @mbg.generated Fri May 05 15:28:30 CST 2017
	 */
	public String getAlias2() {
		return alias2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ujn_hall_double.alias2
	 *
	 * @param alias2
	 *            the value for ujn_hall_double.alias2
	 *
	 * @mbg.generated Fri May 05 15:28:30 CST 2017
	 */
	public void setAlias2(String alias2) {
		this.alias2 = alias2 == null ? null : alias2.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ujn_hall_double.sex2
	 *
	 * @return the value of ujn_hall_double.sex2
	 *
	 * @mbg.generated Fri May 05 15:28:30 CST 2017
	 */
	public String getSex2() {
		return sex2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ujn_hall_double.sex2
	 *
	 * @param sex2
	 *            the value for ujn_hall_double.sex2
	 *
	 * @mbg.generated Fri May 05 15:28:30 CST 2017
	 */
	public void setSex2(String sex2) {
		this.sex2 = sex2 == null ? null : sex2.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ujn_hall_double.nationality2
	 *
	 * @return the value of ujn_hall_double.nationality2
	 *
	 * @mbg.generated Fri May 05 15:28:30 CST 2017
	 */
	public String getNationality2() {
		return nationality2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ujn_hall_double.nationality2
	 *
	 * @param nationality2
	 *            the value for ujn_hall_double.nationality2
	 *
	 * @mbg.generated Fri May 05 15:28:30 CST 2017
	 */
	public void setNationality2(String nationality2) {
		this.nationality2 = nationality2 == null ? null : nationality2.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ujn_hall_double.nation2
	 *
	 * @return the value of ujn_hall_double.nation2
	 *
	 * @mbg.generated Fri May 05 15:28:30 CST 2017
	 */
	public String getNation2() {
		return nation2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ujn_hall_double.nation2
	 *
	 * @param nation2
	 *            the value for ujn_hall_double.nation2
	 *
	 * @mbg.generated Fri May 05 15:28:30 CST 2017
	 */
	public void setNation2(String nation2) {
		this.nation2 = nation2 == null ? null : nation2.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ujn_hall_double.address2
	 *
	 * @return the value of ujn_hall_double.address2
	 *
	 * @mbg.generated Fri May 05 15:28:30 CST 2017
	 */
	public String getAddress2() {
		return address2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ujn_hall_double.address2
	 *
	 * @param address2
	 *            the value for ujn_hall_double.address2
	 *
	 * @mbg.generated Fri May 05 15:28:30 CST 2017
	 */
	public void setAddress2(String address2) {
		this.address2 = address2 == null ? null : address2.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ujn_hall_double.belief2
	 *
	 * @return the value of ujn_hall_double.belief2
	 *
	 * @mbg.generated Fri May 05 15:28:30 CST 2017
	 */
	public String getBelief2() {
		return belief2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ujn_hall_double.belief2
	 *
	 * @param belief2
	 *            the value for ujn_hall_double.belief2
	 *
	 * @mbg.generated Fri May 05 15:28:30 CST 2017
	 */
	public void setBelief2(String belief2) {
		this.belief2 = belief2 == null ? null : belief2.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ujn_hall_double.birthplace2
	 *
	 * @return the value of ujn_hall_double.birthplace2
	 *
	 * @mbg.generated Fri May 05 15:28:30 CST 2017
	 */
	public String getBirthplace2() {
		return birthplace2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ujn_hall_double.birthplace2
	 *
	 * @param birthplace2
	 *            the value for ujn_hall_double.birthplace2
	 *
	 * @mbg.generated Fri May 05 15:28:30 CST 2017
	 */
	public void setBirthplace2(String birthplace2) {
		this.birthplace2 = birthplace2 == null ? null : birthplace2.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ujn_hall_double.native_place2
	 *
	 * @return the value of ujn_hall_double.native_place2
	 *
	 * @mbg.generated Fri May 05 15:28:30 CST 2017
	 */
	public String getNative_place2() {
		return native_place2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ujn_hall_double.native_place2
	 *
	 * @param native_place2
	 *            the value for ujn_hall_double.native_place2
	 *
	 * @mbg.generated Fri May 05 15:28:30 CST 2017
	 */
	public void setNative_place2(String native_place2) {
		this.native_place2 = native_place2 == null ? null : native_place2
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ujn_hall_double.alive_date2
	 *
	 * @return the value of ujn_hall_double.alive_date2
	 *
	 * @mbg.generated Fri May 05 15:28:30 CST 2017
	 */
	public String getAlive_date2() {
		return alive_date2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ujn_hall_double.alive_date2
	 *
	 * @param alive_date2
	 *            the value for ujn_hall_double.alive_date2
	 *
	 * @mbg.generated Fri May 05 15:28:30 CST 2017
	 */
	public void setAlive_date2(String alive_date2) {
		this.alive_date2 = alive_date2 == null ? null : alive_date2.trim();
	}

	public String getZodiac() {
		return zodiac;
	}

	public void setZodiac(String zodiac) {
		this.zodiac = zodiac;
	}

	public String getBirthday() {
		return birthday;
	}

	public void setBirthday(String birthday) {
		this.birthday = birthday;
	}

	public String getDeath_date() {
		return death_date;
	}

	public void setDeath_date(String death_date) {
		this.death_date = death_date;
	}

	public String getZodiac2() {
		return zodiac2;
	}

	public void setZodiac2(String zodiac2) {
		this.zodiac2 = zodiac2;
	}

	public String getBirthday2() {
		return birthday2;
	}

	public void setBirthday2(String birthday2) {
		this.birthday2 = birthday2;
	}

	public String getDeath_date2() {
		return death_date2;
	}

	public void setDeath_date2(String death_date2) {
		this.death_date2 = death_date2;
	}

	public int getDays() {
		return days;
	}

	public void setDays(int days) {
		this.days = days;
	}

	public String getImg_head() {
		return img_head;
	}

	public void setImg_head(String img_head) {
		this.img_head = img_head;
	}

	public String getImg_head2() {
		return img_head2;
	}

	public void setImg_head2(String img_head2) {
		this.img_head2 = img_head2;
	}
}