package com.yuanyuansinian.model.hall;

public class HallDoubleWithBLOBs extends HallDouble {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_hall_double.img_index
     *
     * @mbg.generated Fri May 05 15:28:30 CST 2017
     */
    private byte[] img_index;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_hall_double.achievement
     *
     * @mbg.generated Fri May 05 15:28:30 CST 2017
     */
    private String achievement;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_hall_double.achievement2
     *
     * @mbg.generated Fri May 05 15:28:30 CST 2017
     */
    private String achievement2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_hall_double.img_index
     *
     * @return the value of ujn_hall_double.img_index
     *
     * @mbg.generated Fri May 05 15:28:30 CST 2017
     */
    public byte[] getImg_index() {
        return img_index;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_hall_double.img_index
     *
     * @param img_index the value for ujn_hall_double.img_index
     *
     * @mbg.generated Fri May 05 15:28:30 CST 2017
     */
    public void setImg_index(byte[] img_index) {
        this.img_index = img_index;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_hall_double.achievement
     *
     * @return the value of ujn_hall_double.achievement
     *
     * @mbg.generated Fri May 05 15:28:30 CST 2017
     */
    public String getAchievement() {
        return achievement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_hall_double.achievement
     *
     * @param achievement the value for ujn_hall_double.achievement
     *
     * @mbg.generated Fri May 05 15:28:30 CST 2017
     */
    public void setAchievement(String achievement) {
        this.achievement = achievement == null ? null : achievement.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_hall_double.achievement2
     *
     * @return the value of ujn_hall_double.achievement2
     *
     * @mbg.generated Fri May 05 15:28:30 CST 2017
     */
    public String getAchievement2() {
        return achievement2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_hall_double.achievement2
     *
     * @param achievement2 the value for ujn_hall_double.achievement2
     *
     * @mbg.generated Fri May 05 15:28:30 CST 2017
     */
    public void setAchievement2(String achievement2) {
        this.achievement2 = achievement2 == null ? null : achievement2.trim();
    }
}