package ujn.school.cn.model.content;

public class ContentWithBLOBs extends Content {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_content.content
     *
     * @mbg.generated Mon Mar 27 13:11:59 CST 2017
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_content.description
     *
     * @mbg.generated Mon Mar 27 13:11:59 CST 2017
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_content.tag
     *
     * @mbg.generated Mon Mar 27 13:11:59 CST 2017
     */
    private String tag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_content.content
     *
     * @return the value of ujn_content.content
     *
     * @mbg.generated Mon Mar 27 13:11:59 CST 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_content.content
     *
     * @param content the value for ujn_content.content
     *
     * @mbg.generated Mon Mar 27 13:11:59 CST 2017
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_content.description
     *
     * @return the value of ujn_content.description
     *
     * @mbg.generated Mon Mar 27 13:11:59 CST 2017
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_content.description
     *
     * @param description the value for ujn_content.description
     *
     * @mbg.generated Mon Mar 27 13:11:59 CST 2017
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_content.tag
     *
     * @return the value of ujn_content.tag
     *
     * @mbg.generated Mon Mar 27 13:11:59 CST 2017
     */
    public String getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_content.tag
     *
     * @param tag the value for ujn_content.tag
     *
     * @mbg.generated Mon Mar 27 13:11:59 CST 2017
     */
    public void setTag(String tag) {
        this.tag = tag == null ? null : tag.trim();
    }
}