package ujn.school.cn.model.content;

public class Content {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_content.Id
     *
     * @mbg.generated Mon Feb 20 15:49:48 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_content.title
     *
     * @mbg.generated Mon Feb 20 15:49:48 CST 2017
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_content.ctitle
     *
     * @mbg.generated Mon Feb 20 15:49:48 CST 2017
     */
    private String ctitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_content.keywords
     *
     * @mbg.generated Mon Feb 20 15:49:48 CST 2017
     */
    private String keywords;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_content.class1
     *
     * @mbg.generated Mon Feb 20 15:49:48 CST 2017
     */
    private String class1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_content.class2
     *
     * @mbg.generated Mon Feb 20 15:49:48 CST 2017
     */
    private String class2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_content.class3
     *
     * @mbg.generated Mon Feb 20 15:49:48 CST 2017
     */
    private String class3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_content.class4
     *
     * @mbg.generated Mon Feb 20 15:49:48 CST 2017
     */
    private String class4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_content.no_order
     *
     * @mbg.generated Mon Feb 20 15:49:48 CST 2017
     */
    private String no_order;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_content.new_ok
     *
     * @mbg.generated Mon Feb 20 15:49:48 CST 2017
     */
    private String new_ok;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_content.img_url
     *
     * @mbg.generated Mon Feb 20 15:49:48 CST 2017
     */
    private String img_url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_content.images_url
     *
     * @mbg.generated Mon Feb 20 15:49:48 CST 2017
     */
    private String images_url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_content.cover_img_url
     *
     * @mbg.generated Mon Feb 20 15:49:48 CST 2017
     */
    private String cover_img_url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_content.com_ok
     *
     * @mbg.generated Mon Feb 20 15:49:48 CST 2017
     */
    private String com_ok;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_content.issue
     *
     * @mbg.generated Mon Feb 20 15:49:48 CST 2017
     */
    private String issue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_content.hits
     *
     * @mbg.generated Mon Feb 20 15:49:48 CST 2017
     */
    private Integer hits;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_content.update_time
     *
     * @mbg.generated Mon Feb 20 15:49:48 CST 2017
     */
    private String update_time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_content.add_time
     *
     * @mbg.generated Mon Feb 20 15:49:48 CST 2017
     */
    private String add_time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_content.top_ok
     *
     * @mbg.generated Mon Feb 20 15:49:48 CST 2017
     */
    private String top_ok;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_content.display_type
     *
     * @mbg.generated Mon Feb 20 15:49:48 CST 2017
     */
    private String display_type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_content.links
     *
     * @mbg.generated Mon Feb 20 15:49:48 CST 2017
     */
    private String links;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_content.status
     *
     * @mbg.generated Mon Feb 20 15:49:48 CST 2017
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_content.Id
     *
     * @return the value of ujn_content.Id
     *
     * @mbg.generated Mon Feb 20 15:49:48 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_content.Id
     *
     * @param id the value for ujn_content.Id
     *
     * @mbg.generated Mon Feb 20 15:49:48 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_content.title
     *
     * @return the value of ujn_content.title
     *
     * @mbg.generated Mon Feb 20 15:49:48 CST 2017
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_content.title
     *
     * @param title the value for ujn_content.title
     *
     * @mbg.generated Mon Feb 20 15:49:48 CST 2017
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_content.ctitle
     *
     * @return the value of ujn_content.ctitle
     *
     * @mbg.generated Mon Feb 20 15:49:48 CST 2017
     */
    public String getCtitle() {
        return ctitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_content.ctitle
     *
     * @param ctitle the value for ujn_content.ctitle
     *
     * @mbg.generated Mon Feb 20 15:49:48 CST 2017
     */
    public void setCtitle(String ctitle) {
        this.ctitle = ctitle == null ? null : ctitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_content.keywords
     *
     * @return the value of ujn_content.keywords
     *
     * @mbg.generated Mon Feb 20 15:49:48 CST 2017
     */
    public String getKeywords() {
        return keywords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_content.keywords
     *
     * @param keywords the value for ujn_content.keywords
     *
     * @mbg.generated Mon Feb 20 15:49:48 CST 2017
     */
    public void setKeywords(String keywords) {
        this.keywords = keywords == null ? null : keywords.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_content.class1
     *
     * @return the value of ujn_content.class1
     *
     * @mbg.generated Mon Feb 20 15:49:48 CST 2017
     */
    public String getClass1() {
        return class1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_content.class1
     *
     * @param class1 the value for ujn_content.class1
     *
     * @mbg.generated Mon Feb 20 15:49:48 CST 2017
     */
    public void setClass1(String class1) {
        this.class1 = class1 == null ? null : class1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_content.class2
     *
     * @return the value of ujn_content.class2
     *
     * @mbg.generated Mon Feb 20 15:49:48 CST 2017
     */
    public String getClass2() {
        return class2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_content.class2
     *
     * @param class2 the value for ujn_content.class2
     *
     * @mbg.generated Mon Feb 20 15:49:48 CST 2017
     */
    public void setClass2(String class2) {
        this.class2 = class2 == null ? null : class2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_content.class3
     *
     * @return the value of ujn_content.class3
     *
     * @mbg.generated Mon Feb 20 15:49:48 CST 2017
     */
    public String getClass3() {
        return class3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_content.class3
     *
     * @param class3 the value for ujn_content.class3
     *
     * @mbg.generated Mon Feb 20 15:49:48 CST 2017
     */
    public void setClass3(String class3) {
        this.class3 = class3 == null ? null : class3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_content.class4
     *
     * @return the value of ujn_content.class4
     *
     * @mbg.generated Mon Feb 20 15:49:48 CST 2017
     */
    public String getClass4() {
        return class4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_content.class4
     *
     * @param class4 the value for ujn_content.class4
     *
     * @mbg.generated Mon Feb 20 15:49:48 CST 2017
     */
    public void setClass4(String class4) {
        this.class4 = class4 == null ? null : class4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_content.no_order
     *
     * @return the value of ujn_content.no_order
     *
     * @mbg.generated Mon Feb 20 15:49:48 CST 2017
     */
    public String getNo_order() {
        return no_order;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_content.no_order
     *
     * @param no_order the value for ujn_content.no_order
     *
     * @mbg.generated Mon Feb 20 15:49:48 CST 2017
     */
    public void setNo_order(String no_order) {
        this.no_order = no_order == null ? null : no_order.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_content.new_ok
     *
     * @return the value of ujn_content.new_ok
     *
     * @mbg.generated Mon Feb 20 15:49:48 CST 2017
     */
    public String getNew_ok() {
        return new_ok;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_content.new_ok
     *
     * @param new_ok the value for ujn_content.new_ok
     *
     * @mbg.generated Mon Feb 20 15:49:48 CST 2017
     */
    public void setNew_ok(String new_ok) {
        this.new_ok = new_ok == null ? null : new_ok.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_content.img_url
     *
     * @return the value of ujn_content.img_url
     *
     * @mbg.generated Mon Feb 20 15:49:48 CST 2017
     */
    public String getImg_url() {
        return img_url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_content.img_url
     *
     * @param img_url the value for ujn_content.img_url
     *
     * @mbg.generated Mon Feb 20 15:49:48 CST 2017
     */
    public void setImg_url(String img_url) {
        this.img_url = img_url == null ? null : img_url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_content.images_url
     *
     * @return the value of ujn_content.images_url
     *
     * @mbg.generated Mon Feb 20 15:49:48 CST 2017
     */
    public String getImages_url() {
        return images_url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_content.images_url
     *
     * @param images_url the value for ujn_content.images_url
     *
     * @mbg.generated Mon Feb 20 15:49:48 CST 2017
     */
    public void setImages_url(String images_url) {
        this.images_url = images_url == null ? null : images_url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_content.cover_img_url
     *
     * @return the value of ujn_content.cover_img_url
     *
     * @mbg.generated Mon Feb 20 15:49:48 CST 2017
     */
    public String getCover_img_url() {
        return cover_img_url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_content.cover_img_url
     *
     * @param cover_img_url the value for ujn_content.cover_img_url
     *
     * @mbg.generated Mon Feb 20 15:49:48 CST 2017
     */
    public void setCover_img_url(String cover_img_url) {
        this.cover_img_url = cover_img_url == null ? null : cover_img_url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_content.com_ok
     *
     * @return the value of ujn_content.com_ok
     *
     * @mbg.generated Mon Feb 20 15:49:48 CST 2017
     */
    public String getCom_ok() {
        return com_ok;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_content.com_ok
     *
     * @param com_ok the value for ujn_content.com_ok
     *
     * @mbg.generated Mon Feb 20 15:49:48 CST 2017
     */
    public void setCom_ok(String com_ok) {
        this.com_ok = com_ok == null ? null : com_ok.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_content.issue
     *
     * @return the value of ujn_content.issue
     *
     * @mbg.generated Mon Feb 20 15:49:48 CST 2017
     */
    public String getIssue() {
        return issue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_content.issue
     *
     * @param issue the value for ujn_content.issue
     *
     * @mbg.generated Mon Feb 20 15:49:48 CST 2017
     */
    public void setIssue(String issue) {
        this.issue = issue == null ? null : issue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_content.hits
     *
     * @return the value of ujn_content.hits
     *
     * @mbg.generated Mon Feb 20 15:49:48 CST 2017
     */
    public Integer getHits() {
        return hits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_content.hits
     *
     * @param hits the value for ujn_content.hits
     *
     * @mbg.generated Mon Feb 20 15:49:48 CST 2017
     */
    public void setHits(Integer hits) {
        this.hits = hits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_content.update_time
     *
     * @return the value of ujn_content.update_time
     *
     * @mbg.generated Mon Feb 20 15:49:48 CST 2017
     */
    public String getUpdate_time() {
        return update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_content.update_time
     *
     * @param update_time the value for ujn_content.update_time
     *
     * @mbg.generated Mon Feb 20 15:49:48 CST 2017
     */
    public void setUpdate_time(String update_time) {
        this.update_time = update_time == null ? null : update_time.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_content.add_time
     *
     * @return the value of ujn_content.add_time
     *
     * @mbg.generated Mon Feb 20 15:49:48 CST 2017
     */
    public String getAdd_time() {
        return add_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_content.add_time
     *
     * @param add_time the value for ujn_content.add_time
     *
     * @mbg.generated Mon Feb 20 15:49:48 CST 2017
     */
    public void setAdd_time(String add_time) {
        this.add_time = add_time == null ? null : add_time.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_content.top_ok
     *
     * @return the value of ujn_content.top_ok
     *
     * @mbg.generated Mon Feb 20 15:49:48 CST 2017
     */
    public String getTop_ok() {
        return top_ok;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_content.top_ok
     *
     * @param top_ok the value for ujn_content.top_ok
     *
     * @mbg.generated Mon Feb 20 15:49:48 CST 2017
     */
    public void setTop_ok(String top_ok) {
        this.top_ok = top_ok == null ? null : top_ok.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_content.display_type
     *
     * @return the value of ujn_content.display_type
     *
     * @mbg.generated Mon Feb 20 15:49:48 CST 2017
     */
    public String getDisplay_type() {
        return display_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_content.display_type
     *
     * @param display_type the value for ujn_content.display_type
     *
     * @mbg.generated Mon Feb 20 15:49:48 CST 2017
     */
    public void setDisplay_type(String display_type) {
        this.display_type = display_type == null ? null : display_type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_content.links
     *
     * @return the value of ujn_content.links
     *
     * @mbg.generated Mon Feb 20 15:49:48 CST 2017
     */
    public String getLinks() {
        return links;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_content.links
     *
     * @param links the value for ujn_content.links
     *
     * @mbg.generated Mon Feb 20 15:49:48 CST 2017
     */
    public void setLinks(String links) {
        this.links = links == null ? null : links.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_content.status
     *
     * @return the value of ujn_content.status
     *
     * @mbg.generated Mon Feb 20 15:49:48 CST 2017
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_content.status
     *
     * @param status the value for ujn_content.status
     *
     * @mbg.generated Mon Feb 20 15:49:48 CST 2017
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
}