package ujn.school.cn.model.content;

public class Content {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_content.Id
     *
     * @mbg.generated Thu Apr 06 10:25:09 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_content.code_num
     *
     * @mbg.generated Thu Apr 06 10:25:09 CST 2017
     */
    private String code_num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_content.title
     *
     * @mbg.generated Thu Apr 06 10:25:09 CST 2017
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_content.ctitle
     *
     * @mbg.generated Thu Apr 06 10:25:09 CST 2017
     */
    private String ctitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_content.keywords
     *
     * @mbg.generated Thu Apr 06 10:25:09 CST 2017
     */
    private String keywords;
    
    private String order_column;
    
    private String order_type;
    
    private int count_num;
    
    private String startDate;
    private String endDate;
    private String count;
    
    //显示的条数
    private int limit_num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_content.column_id
     *
     * @mbg.generated Thu Apr 06 10:25:09 CST 2017
     */
    private String column_id;
    private String column_id_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_content.class1
     *
     * @mbg.generated Thu Apr 06 10:25:09 CST 2017
     */
    private String class1;
    private String class1_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_content.class2
     *
     * @mbg.generated Thu Apr 06 10:25:09 CST 2017
     */
    private String class2;
    private String class2_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_content.class3
     *
     * @mbg.generated Thu Apr 06 10:25:09 CST 2017
     */
    private String class3;
    private String class3_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_content.class4
     *
     * @mbg.generated Thu Apr 06 10:25:09 CST 2017
     */
    private String class4;
    private String class4_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_content.no_order
     *
     * @mbg.generated Thu Apr 06 10:25:09 CST 2017
     */
    private String no_order;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_content.new_ok
     *
     * @mbg.generated Thu Apr 06 10:25:09 CST 2017
     */
    private String new_ok;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_content.img_url
     *
     * @mbg.generated Thu Apr 06 10:25:09 CST 2017
     */
    private String img_url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_content.images_url
     *
     * @mbg.generated Thu Apr 06 10:25:09 CST 2017
     */
    private String images_url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_content.cover_img_url
     *
     * @mbg.generated Thu Apr 06 10:25:09 CST 2017
     */
    private String cover_img_url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_content.com_ok
     *
     * @mbg.generated Thu Apr 06 10:25:09 CST 2017
     */
    private String com_ok;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_content.issue
     *
     * @mbg.generated Thu Apr 06 10:25:09 CST 2017
     */
    private String issue;
    private String issue_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_content.hits
     *
     * @mbg.generated Thu Apr 06 10:25:09 CST 2017
     */
    private Integer hits;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_content.update_time
     *
     * @mbg.generated Thu Apr 06 10:25:09 CST 2017
     */
    private String update_time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_content.add_time
     *
     * @mbg.generated Thu Apr 06 10:25:09 CST 2017
     */
    private String add_time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_content.top_ok
     *
     * @mbg.generated Thu Apr 06 10:25:09 CST 2017
     */
    private String top_ok;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_content.display_type
     *
     * @mbg.generated Thu Apr 06 10:25:09 CST 2017
     */
    private String display_type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_content.validity_time
     *
     * @mbg.generated Thu Apr 06 10:25:09 CST 2017
     */
    private String validity_time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_content.links
     *
     * @mbg.generated Thu Apr 06 10:25:09 CST 2017
     */
    private String links;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_content.status
     *
     * @mbg.generated Thu Apr 06 10:25:09 CST 2017
     */
    private String status;
    private String status_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_content.read_type
     *
     * @mbg.generated Thu Apr 06 10:25:09 CST 2017
     */
    private String read_type;
    private String read_type_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_content.read_pwd
     *
     * @mbg.generated Thu Apr 06 10:25:09 CST 2017
     */
    private String read_pwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_content.importance
     *
     * @mbg.generated Thu Apr 06 10:25:09 CST 2017
     */
    private String importance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_content.open_code
     *
     * @mbg.generated Thu Apr 06 10:25:09 CST 2017
     */
    private String open_code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_content.dept_code
     *
     * @mbg.generated Thu Apr 06 10:25:09 CST 2017
     */
    private String dept_code;
    private String dept_code_name;

    public String getDept_code_name() {
		return dept_code_name;
	}

	public void setDept_code_name(String dept_code_name) {
		this.dept_code_name = dept_code_name;
	}

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_content.class_code
     *
     * @mbg.generated Thu Apr 06 10:25:09 CST 2017
     */
    private String class_code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_content.year_code
     *
     * @mbg.generated Thu Apr 06 10:25:09 CST 2017
     */
    private String year_code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_content.order_code
     *
     * @mbg.generated Thu Apr 06 10:25:09 CST 2017
     */
    private String order_code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_content.open_type_code
     *
     * @mbg.generated Thu Apr 06 10:25:09 CST 2017
     */
    private String open_type_code;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_content.Id
     *
     * @return the value of ujn_content.Id
     *
     * @mbg.generated Thu Apr 06 10:25:09 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_content.Id
     *
     * @param id the value for ujn_content.Id
     *
     * @mbg.generated Thu Apr 06 10:25:09 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_content.code_num
     *
     * @return the value of ujn_content.code_num
     *
     * @mbg.generated Thu Apr 06 10:25:09 CST 2017
     */
    public String getCode_num() {
        return code_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_content.code_num
     *
     * @param code_num the value for ujn_content.code_num
     *
     * @mbg.generated Thu Apr 06 10:25:09 CST 2017
     */
    public void setCode_num(String code_num) {
        this.code_num = code_num == null ? null : code_num.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_content.title
     *
     * @return the value of ujn_content.title
     *
     * @mbg.generated Thu Apr 06 10:25:09 CST 2017
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_content.title
     *
     * @param title the value for ujn_content.title
     *
     * @mbg.generated Thu Apr 06 10:25:09 CST 2017
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_content.ctitle
     *
     * @return the value of ujn_content.ctitle
     *
     * @mbg.generated Thu Apr 06 10:25:09 CST 2017
     */
    public String getCtitle() {
        return ctitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_content.ctitle
     *
     * @param ctitle the value for ujn_content.ctitle
     *
     * @mbg.generated Thu Apr 06 10:25:09 CST 2017
     */
    public void setCtitle(String ctitle) {
        this.ctitle = ctitle == null ? null : ctitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_content.keywords
     *
     * @return the value of ujn_content.keywords
     *
     * @mbg.generated Thu Apr 06 10:25:09 CST 2017
     */
    public String getKeywords() {
        return keywords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_content.keywords
     *
     * @param keywords the value for ujn_content.keywords
     *
     * @mbg.generated Thu Apr 06 10:25:09 CST 2017
     */
    public void setKeywords(String keywords) {
        this.keywords = keywords == null ? null : keywords.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_content.column_id
     *
     * @return the value of ujn_content.column_id
     *
     * @mbg.generated Thu Apr 06 10:25:09 CST 2017
     */
    public String getColumn_id() {
        return column_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_content.column_id
     *
     * @param column_id the value for ujn_content.column_id
     *
     * @mbg.generated Thu Apr 06 10:25:09 CST 2017
     */
    public void setColumn_id(String column_id) {
        this.column_id = column_id == null ? null : column_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_content.class1
     *
     * @return the value of ujn_content.class1
     *
     * @mbg.generated Thu Apr 06 10:25:09 CST 2017
     */
    public String getClass1() {
        return class1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_content.class1
     *
     * @param class1 the value for ujn_content.class1
     *
     * @mbg.generated Thu Apr 06 10:25:09 CST 2017
     */
    public void setClass1(String class1) {
        this.class1 = class1 == null ? null : class1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_content.class2
     *
     * @return the value of ujn_content.class2
     *
     * @mbg.generated Thu Apr 06 10:25:09 CST 2017
     */
    public String getClass2() {
        return class2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_content.class2
     *
     * @param class2 the value for ujn_content.class2
     *
     * @mbg.generated Thu Apr 06 10:25:09 CST 2017
     */
    public void setClass2(String class2) {
        this.class2 = class2 == null ? null : class2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_content.class3
     *
     * @return the value of ujn_content.class3
     *
     * @mbg.generated Thu Apr 06 10:25:09 CST 2017
     */
    public String getClass3() {
        return class3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_content.class3
     *
     * @param class3 the value for ujn_content.class3
     *
     * @mbg.generated Thu Apr 06 10:25:09 CST 2017
     */
    public void setClass3(String class3) {
        this.class3 = class3 == null ? null : class3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_content.class4
     *
     * @return the value of ujn_content.class4
     *
     * @mbg.generated Thu Apr 06 10:25:09 CST 2017
     */
    public String getClass4() {
        return class4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_content.class4
     *
     * @param class4 the value for ujn_content.class4
     *
     * @mbg.generated Thu Apr 06 10:25:09 CST 2017
     */
    public void setClass4(String class4) {
        this.class4 = class4 == null ? null : class4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_content.no_order
     *
     * @return the value of ujn_content.no_order
     *
     * @mbg.generated Thu Apr 06 10:25:09 CST 2017
     */
    public String getNo_order() {
        return no_order;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_content.no_order
     *
     * @param no_order the value for ujn_content.no_order
     *
     * @mbg.generated Thu Apr 06 10:25:09 CST 2017
     */
    public void setNo_order(String no_order) {
        this.no_order = no_order == null ? null : no_order.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_content.new_ok
     *
     * @return the value of ujn_content.new_ok
     *
     * @mbg.generated Thu Apr 06 10:25:09 CST 2017
     */
    public String getNew_ok() {
        return new_ok;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_content.new_ok
     *
     * @param new_ok the value for ujn_content.new_ok
     *
     * @mbg.generated Thu Apr 06 10:25:09 CST 2017
     */
    public void setNew_ok(String new_ok) {
        this.new_ok = new_ok == null ? null : new_ok.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_content.img_url
     *
     * @return the value of ujn_content.img_url
     *
     * @mbg.generated Thu Apr 06 10:25:09 CST 2017
     */
    public String getImg_url() {
        return img_url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_content.img_url
     *
     * @param img_url the value for ujn_content.img_url
     *
     * @mbg.generated Thu Apr 06 10:25:09 CST 2017
     */
    public void setImg_url(String img_url) {
        this.img_url = img_url == null ? null : img_url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_content.images_url
     *
     * @return the value of ujn_content.images_url
     *
     * @mbg.generated Thu Apr 06 10:25:09 CST 2017
     */
    public String getImages_url() {
        return images_url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_content.images_url
     *
     * @param images_url the value for ujn_content.images_url
     *
     * @mbg.generated Thu Apr 06 10:25:09 CST 2017
     */
    public void setImages_url(String images_url) {
        this.images_url = images_url == null ? null : images_url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_content.cover_img_url
     *
     * @return the value of ujn_content.cover_img_url
     *
     * @mbg.generated Thu Apr 06 10:25:09 CST 2017
     */
    public String getCover_img_url() {
        return cover_img_url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_content.cover_img_url
     *
     * @param cover_img_url the value for ujn_content.cover_img_url
     *
     * @mbg.generated Thu Apr 06 10:25:09 CST 2017
     */
    public void setCover_img_url(String cover_img_url) {
        this.cover_img_url = cover_img_url == null ? null : cover_img_url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_content.com_ok
     *
     * @return the value of ujn_content.com_ok
     *
     * @mbg.generated Thu Apr 06 10:25:09 CST 2017
     */
    public String getCom_ok() {
        return com_ok;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_content.com_ok
     *
     * @param com_ok the value for ujn_content.com_ok
     *
     * @mbg.generated Thu Apr 06 10:25:09 CST 2017
     */
    public void setCom_ok(String com_ok) {
        this.com_ok = com_ok == null ? null : com_ok.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_content.issue
     *
     * @return the value of ujn_content.issue
     *
     * @mbg.generated Thu Apr 06 10:25:09 CST 2017
     */
    public String getIssue() {
        return issue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_content.issue
     *
     * @param issue the value for ujn_content.issue
     *
     * @mbg.generated Thu Apr 06 10:25:09 CST 2017
     */
    public void setIssue(String issue) {
        this.issue = issue == null ? null : issue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_content.hits
     *
     * @return the value of ujn_content.hits
     *
     * @mbg.generated Thu Apr 06 10:25:09 CST 2017
     */
    public Integer getHits() {
        return hits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_content.hits
     *
     * @param hits the value for ujn_content.hits
     *
     * @mbg.generated Thu Apr 06 10:25:09 CST 2017
     */
    public void setHits(Integer hits) {
        this.hits = hits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_content.update_time
     *
     * @return the value of ujn_content.update_time
     *
     * @mbg.generated Thu Apr 06 10:25:09 CST 2017
     */
    public String getUpdate_time() {
        return update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_content.update_time
     *
     * @param update_time the value for ujn_content.update_time
     *
     * @mbg.generated Thu Apr 06 10:25:09 CST 2017
     */
    public void setUpdate_time(String update_time) {
        this.update_time = update_time == null ? null : update_time.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_content.add_time
     *
     * @return the value of ujn_content.add_time
     *
     * @mbg.generated Thu Apr 06 10:25:09 CST 2017
     */
    public String getAdd_time() {
        return add_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_content.add_time
     *
     * @param add_time the value for ujn_content.add_time
     *
     * @mbg.generated Thu Apr 06 10:25:09 CST 2017
     */
    public void setAdd_time(String add_time) {
        this.add_time = add_time == null ? null : add_time.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_content.top_ok
     *
     * @return the value of ujn_content.top_ok
     *
     * @mbg.generated Thu Apr 06 10:25:09 CST 2017
     */
    public String getTop_ok() {
        return top_ok;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_content.top_ok
     *
     * @param top_ok the value for ujn_content.top_ok
     *
     * @mbg.generated Thu Apr 06 10:25:09 CST 2017
     */
    public void setTop_ok(String top_ok) {
        this.top_ok = top_ok == null ? null : top_ok.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_content.display_type
     *
     * @return the value of ujn_content.display_type
     *
     * @mbg.generated Thu Apr 06 10:25:09 CST 2017
     */
    public String getDisplay_type() {
        return display_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_content.display_type
     *
     * @param display_type the value for ujn_content.display_type
     *
     * @mbg.generated Thu Apr 06 10:25:09 CST 2017
     */
    public void setDisplay_type(String display_type) {
        this.display_type = display_type == null ? null : display_type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_content.validity_time
     *
     * @return the value of ujn_content.validity_time
     *
     * @mbg.generated Thu Apr 06 10:25:09 CST 2017
     */
    public String getValidity_time() {
        return validity_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_content.validity_time
     *
     * @param validity_time the value for ujn_content.validity_time
     *
     * @mbg.generated Thu Apr 06 10:25:09 CST 2017
     */
    public void setValidity_time(String validity_time) {
        this.validity_time = validity_time == null ? null : validity_time.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_content.links
     *
     * @return the value of ujn_content.links
     *
     * @mbg.generated Thu Apr 06 10:25:09 CST 2017
     */
    public String getLinks() {
        return links;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_content.links
     *
     * @param links the value for ujn_content.links
     *
     * @mbg.generated Thu Apr 06 10:25:09 CST 2017
     */
    public void setLinks(String links) {
        this.links = links == null ? null : links.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_content.status
     *
     * @return the value of ujn_content.status
     *
     * @mbg.generated Thu Apr 06 10:25:09 CST 2017
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_content.status
     *
     * @param status the value for ujn_content.status
     *
     * @mbg.generated Thu Apr 06 10:25:09 CST 2017
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_content.read_type
     *
     * @return the value of ujn_content.read_type
     *
     * @mbg.generated Thu Apr 06 10:25:09 CST 2017
     */
    public String getRead_type() {
        return read_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_content.read_type
     *
     * @param read_type the value for ujn_content.read_type
     *
     * @mbg.generated Thu Apr 06 10:25:09 CST 2017
     */
    public void setRead_type(String read_type) {
        this.read_type = read_type == null ? null : read_type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_content.read_pwd
     *
     * @return the value of ujn_content.read_pwd
     *
     * @mbg.generated Thu Apr 06 10:25:09 CST 2017
     */
    public String getRead_pwd() {
        return read_pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_content.read_pwd
     *
     * @param read_pwd the value for ujn_content.read_pwd
     *
     * @mbg.generated Thu Apr 06 10:25:09 CST 2017
     */
    public void setRead_pwd(String read_pwd) {
        this.read_pwd = read_pwd == null ? null : read_pwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_content.importance
     *
     * @return the value of ujn_content.importance
     *
     * @mbg.generated Thu Apr 06 10:25:09 CST 2017
     */
    public String getImportance() {
        return importance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_content.importance
     *
     * @param importance the value for ujn_content.importance
     *
     * @mbg.generated Thu Apr 06 10:25:09 CST 2017
     */
    public void setImportance(String importance) {
        this.importance = importance == null ? null : importance.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_content.open_code
     *
     * @return the value of ujn_content.open_code
     *
     * @mbg.generated Thu Apr 06 10:25:09 CST 2017
     */
    public String getOpen_code() {
        return open_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_content.open_code
     *
     * @param open_code the value for ujn_content.open_code
     *
     * @mbg.generated Thu Apr 06 10:25:09 CST 2017
     */
    public void setOpen_code(String open_code) {
        this.open_code = open_code == null ? null : open_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_content.dept_code
     *
     * @return the value of ujn_content.dept_code
     *
     * @mbg.generated Thu Apr 06 10:25:09 CST 2017
     */
    public String getDept_code() {
        return dept_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_content.dept_code
     *
     * @param dept_code the value for ujn_content.dept_code
     *
     * @mbg.generated Thu Apr 06 10:25:09 CST 2017
     */
    public void setDept_code(String dept_code) {
        this.dept_code = dept_code == null ? null : dept_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_content.class_code
     *
     * @return the value of ujn_content.class_code
     *
     * @mbg.generated Thu Apr 06 10:25:09 CST 2017
     */
    public String getClass_code() {
        return class_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_content.class_code
     *
     * @param class_code the value for ujn_content.class_code
     *
     * @mbg.generated Thu Apr 06 10:25:09 CST 2017
     */
    public void setClass_code(String class_code) {
        this.class_code = class_code == null ? null : class_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_content.year_code
     *
     * @return the value of ujn_content.year_code
     *
     * @mbg.generated Thu Apr 06 10:25:09 CST 2017
     */
    public String getYear_code() {
        return year_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_content.year_code
     *
     * @param year_code the value for ujn_content.year_code
     *
     * @mbg.generated Thu Apr 06 10:25:09 CST 2017
     */
    public void setYear_code(String year_code) {
        this.year_code = year_code == null ? null : year_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_content.order_code
     *
     * @return the value of ujn_content.order_code
     *
     * @mbg.generated Thu Apr 06 10:25:09 CST 2017
     */
    public String getOrder_code() {
        return order_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_content.order_code
     *
     * @param order_code the value for ujn_content.order_code
     *
     * @mbg.generated Thu Apr 06 10:25:09 CST 2017
     */
    public void setOrder_code(String order_code) {
        this.order_code = order_code == null ? null : order_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_content.open_type_code
     *
     * @return the value of ujn_content.open_type_code
     *
     * @mbg.generated Thu Apr 06 10:25:09 CST 2017
     */
    public String getOpen_type_code() {
        return open_type_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_content.open_type_code
     *
     * @param open_type_code the value for ujn_content.open_type_code
     *
     * @mbg.generated Thu Apr 06 10:25:09 CST 2017
     */
    public void setOpen_type_code(String open_type_code) {
        this.open_type_code = open_type_code == null ? null : open_type_code.trim();
    }

	public String getOrder_column() {
		return order_column;
	}

	public void setOrder_column(String order_column) {
		this.order_column = order_column;
	}

	public String getOrder_type() {
		return order_type;
	}

	public void setOrder_type(String order_type) {
		this.order_type = order_type;
	}

	public int getCount_num() {
		return count_num;
	}

	public void setCount_num(int count_num) {
		this.count_num = count_num;
	}

	public String getColumn_id_name() {
		return column_id_name;
	}

	public void setColumn_id_name(String column_id_name) {
		this.column_id_name = column_id_name;
	}

	public String getClass1_name() {
		return class1_name;
	}

	public void setClass1_name(String class1_name) {
		this.class1_name = class1_name;
	}

	public String getClass2_name() {
		return class2_name;
	}

	public void setClass2_name(String class2_name) {
		this.class2_name = class2_name;
	}

	public String getClass3_name() {
		return class3_name;
	}

	public void setClass3_name(String class3_name) {
		this.class3_name = class3_name;
	}

	public String getClass4_name() {
		return class4_name;
	}

	public void setClass4_name(String class4_name) {
		this.class4_name = class4_name;
	}

	public String getIssue_name() {
		return issue_name;
	}

	public void setIssue_name(String issue_name) {
		this.issue_name = issue_name;
	}

	public String getStatus_name() {
		return status_name;
	}

	public void setStatus_name(String status_name) {
		this.status_name = status_name;
	}

	public String getRead_type_name() {
		return read_type_name;
	}

	public void setRead_type_name(String read_type_name) {
		this.read_type_name = read_type_name;
	}

	public int getLimit_num() {
		return limit_num;
	}

	public void setLimit_num(int limit_num) {
		this.limit_num = limit_num;
	}

	public String getStartDate() {
		return startDate;
	}

	public void setStartDate(String startDate) {
		this.startDate = startDate;
	}

	public String getEndDate() {
		return endDate;
	}

	public void setEndDate(String endDate) {
		this.endDate = endDate;
	}

	public String getCount() {
		return count;
	}

	public void setCount(String count) {
		this.count = count;
	}
}