package com.yuanyuansinian.dao.warehouse;

import java.util.List;

import com.yuanyuansinian.model.warehouse.Warehouse;

public interface WarehouseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujn_warehouse
     *
     * @mbg.generated Fri May 12 17:35:29 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujn_warehouse
     *
     * @mbg.generated Fri May 12 17:35:29 CST 2017
     */
    int insert(Warehouse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujn_warehouse
     *
     * @mbg.generated Fri May 12 17:35:29 CST 2017
     */
    int insertSelective(Warehouse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujn_warehouse
     *
     * @mbg.generated Fri May 12 17:35:29 CST 2017
     */
    Warehouse selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujn_warehouse
     *
     * @mbg.generated Fri May 12 17:35:29 CST 2017
     */
    int updateByPrimaryKeySelective(Warehouse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujn_warehouse
     *
     * @mbg.generated Fri May 12 17:35:29 CST 2017
     */
    int updateByPrimaryKey(Warehouse record);

	List<Warehouse> queryWarehouseListByType(String type);

	List<Warehouse> queryWarehouseList(Warehouse warehouse);
}