package ujn.school.cn.dao.link;

import java.util.List;

import ujn.school.cn.model.link.Link;

public interface LinkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujn_link
     *
     * @mbg.generated Thu Feb 09 23:11:40 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujn_link
     *
     * @mbg.generated Thu Feb 09 23:11:40 CST 2017
     */
    int insert(Link record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujn_link
     *
     * @mbg.generated Thu Feb 09 23:11:40 CST 2017
     */
    int insertSelective(Link record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujn_link
     *
     * @mbg.generated Thu Feb 09 23:11:40 CST 2017
     */
    Link selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujn_link
     *
     * @mbg.generated Thu Feb 09 23:11:40 CST 2017
     */
    int updateByPrimaryKeySelective(Link record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujn_link
     *
     * @mbg.generated Thu Feb 09 23:11:40 CST 2017
     */
    int updateByPrimaryKey(Link record);

	List<Link> queryLinkList(Link link);
}