package com.yuanyuansinian.model.link;

public class Link {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_link.Id
     *
     * @mbg.generated Wed Feb 15 15:48:34 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_link.web_name
     *
     * @mbg.generated Wed Feb 15 15:48:34 CST 2017
     */
    private String web_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_link.web_url
     *
     * @mbg.generated Wed Feb 15 15:48:34 CST 2017
     */
    private String web_url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_link.web_logo
     *
     * @mbg.generated Wed Feb 15 15:48:34 CST 2017
     */
    private String web_logo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_link.link_type
     *
     * @mbg.generated Wed Feb 15 15:48:34 CST 2017
     */
    private String link_type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_link.info
     *
     * @mbg.generated Wed Feb 15 15:48:34 CST 2017
     */
    private String info;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_link.contact
     *
     * @mbg.generated Wed Feb 15 15:48:34 CST 2017
     */
    private String contact;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_link.order_no
     *
     * @mbg.generated Wed Feb 15 15:48:34 CST 2017
     */
    private Integer order_no;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_link.show_ok
     *
     * @mbg.generated Wed Feb 15 15:48:34 CST 2017
     */
    private String show_ok;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_link.add_time
     *
     * @mbg.generated Wed Feb 15 15:48:34 CST 2017
     */
    private String add_time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_link.Id
     *
     * @return the value of ujn_link.Id
     *
     * @mbg.generated Wed Feb 15 15:48:34 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_link.Id
     *
     * @param id the value for ujn_link.Id
     *
     * @mbg.generated Wed Feb 15 15:48:34 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_link.web_name
     *
     * @return the value of ujn_link.web_name
     *
     * @mbg.generated Wed Feb 15 15:48:34 CST 2017
     */
    public String getWeb_name() {
        return web_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_link.web_name
     *
     * @param web_name the value for ujn_link.web_name
     *
     * @mbg.generated Wed Feb 15 15:48:34 CST 2017
     */
    public void setWeb_name(String web_name) {
        this.web_name = web_name == null ? null : web_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_link.web_url
     *
     * @return the value of ujn_link.web_url
     *
     * @mbg.generated Wed Feb 15 15:48:34 CST 2017
     */
    public String getWeb_url() {
        return web_url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_link.web_url
     *
     * @param web_url the value for ujn_link.web_url
     *
     * @mbg.generated Wed Feb 15 15:48:34 CST 2017
     */
    public void setWeb_url(String web_url) {
        this.web_url = web_url == null ? null : web_url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_link.web_logo
     *
     * @return the value of ujn_link.web_logo
     *
     * @mbg.generated Wed Feb 15 15:48:34 CST 2017
     */
    public String getWeb_logo() {
        return web_logo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_link.web_logo
     *
     * @param web_logo the value for ujn_link.web_logo
     *
     * @mbg.generated Wed Feb 15 15:48:34 CST 2017
     */
    public void setWeb_logo(String web_logo) {
        this.web_logo = web_logo == null ? null : web_logo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_link.link_type
     *
     * @return the value of ujn_link.link_type
     *
     * @mbg.generated Wed Feb 15 15:48:34 CST 2017
     */
    public String getLink_type() {
        return link_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_link.link_type
     *
     * @param link_type the value for ujn_link.link_type
     *
     * @mbg.generated Wed Feb 15 15:48:34 CST 2017
     */
    public void setLink_type(String link_type) {
        this.link_type = link_type == null ? null : link_type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_link.info
     *
     * @return the value of ujn_link.info
     *
     * @mbg.generated Wed Feb 15 15:48:34 CST 2017
     */
    public String getInfo() {
        return info;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_link.info
     *
     * @param info the value for ujn_link.info
     *
     * @mbg.generated Wed Feb 15 15:48:34 CST 2017
     */
    public void setInfo(String info) {
        this.info = info == null ? null : info.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_link.contact
     *
     * @return the value of ujn_link.contact
     *
     * @mbg.generated Wed Feb 15 15:48:34 CST 2017
     */
    public String getContact() {
        return contact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_link.contact
     *
     * @param contact the value for ujn_link.contact
     *
     * @mbg.generated Wed Feb 15 15:48:34 CST 2017
     */
    public void setContact(String contact) {
        this.contact = contact == null ? null : contact.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_link.order_no
     *
     * @return the value of ujn_link.order_no
     *
     * @mbg.generated Wed Feb 15 15:48:34 CST 2017
     */
    public Integer getOrder_no() {
        return order_no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_link.order_no
     *
     * @param order_no the value for ujn_link.order_no
     *
     * @mbg.generated Wed Feb 15 15:48:34 CST 2017
     */
    public void setOrder_no(Integer order_no) {
        this.order_no = order_no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_link.show_ok
     *
     * @return the value of ujn_link.show_ok
     *
     * @mbg.generated Wed Feb 15 15:48:34 CST 2017
     */
    public String getShow_ok() {
        return show_ok;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_link.show_ok
     *
     * @param show_ok the value for ujn_link.show_ok
     *
     * @mbg.generated Wed Feb 15 15:48:34 CST 2017
     */
    public void setShow_ok(String show_ok) {
        this.show_ok = show_ok == null ? null : show_ok.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_link.add_time
     *
     * @return the value of ujn_link.add_time
     *
     * @mbg.generated Wed Feb 15 15:48:34 CST 2017
     */
    public String getAdd_time() {
        return add_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_link.add_time
     *
     * @param add_time the value for ujn_link.add_time
     *
     * @mbg.generated Wed Feb 15 15:48:34 CST 2017
     */
    public void setAdd_time(String add_time) {
        this.add_time = add_time == null ? null : add_time.trim();
    }
}