package com.yuanyuansinian.model.product;

public class Product {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_product.Id
     *
     * @mbg.generated Wed Mar 08 14:45:29 CST 2017
     */
    private Integer id;
    private String product_no;
    private Integer sales;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_product.name
     *
     * @mbg.generated Wed Mar 08 14:45:29 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_product.name_short
     *
     * @mbg.generated Wed Mar 08 14:45:29 CST 2017
     */
    private String name_short;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_product.price_market
     *
     * @mbg.generated Wed Mar 08 14:45:29 CST 2017
     */
    private Double price_market;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_product.price_site
     *
     * @mbg.generated Wed Mar 08 14:45:29 CST 2017
     */
    private Double price_site;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_product.price_cost
     *
     * @mbg.generated Wed Mar 08 14:45:29 CST 2017
     */
    private Double price_cost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_product.price_min
     *
     * @mbg.generated Wed Mar 08 14:45:29 CST 2017
     */
    private Double price_min;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_product.units
     *
     * @mbg.generated Wed Mar 08 14:45:29 CST 2017
     */
    private String units;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_product.description
     *
     * @mbg.generated Wed Mar 08 14:45:29 CST 2017
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_product.status
     *
     * @mbg.generated Wed Mar 08 14:45:29 CST 2017
     */
    private String status;
    private String status_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_product.create_date
     *
     * @mbg.generated Wed Mar 08 14:45:29 CST 2017
     */
    private String create_date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_product.keywords
     *
     * @mbg.generated Wed Mar 08 14:45:29 CST 2017
     */
    private String keywords;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_product.pic
     *
     * @mbg.generated Wed Mar 08 14:45:29 CST 2017
     */
    private String pic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_product.type
     *
     * @mbg.generated Wed Mar 08 14:45:29 CST 2017
     */
    private String type;
    private String type_name;
    private String big_type;
    private String big_type_name;
    
    
    private int no_order;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_product.Id
     *
     * @return the value of ujn_product.Id
     *
     * @mbg.generated Wed Mar 08 14:45:29 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_product.Id
     *
     * @param id the value for ujn_product.Id
     *
     * @mbg.generated Wed Mar 08 14:45:29 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_product.name
     *
     * @return the value of ujn_product.name
     *
     * @mbg.generated Wed Mar 08 14:45:29 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_product.name
     *
     * @param name the value for ujn_product.name
     *
     * @mbg.generated Wed Mar 08 14:45:29 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_product.name_short
     *
     * @return the value of ujn_product.name_short
     *
     * @mbg.generated Wed Mar 08 14:45:29 CST 2017
     */
    public String getName_short() {
        return name_short;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_product.name_short
     *
     * @param name_short the value for ujn_product.name_short
     *
     * @mbg.generated Wed Mar 08 14:45:29 CST 2017
     */
    public void setName_short(String name_short) {
        this.name_short = name_short == null ? null : name_short.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_product.price_market
     *
     * @return the value of ujn_product.price_market
     *
     * @mbg.generated Wed Mar 08 14:45:29 CST 2017
     */
    public Double getPrice_market() {
        return price_market;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_product.price_market
     *
     * @param price_market the value for ujn_product.price_market
     *
     * @mbg.generated Wed Mar 08 14:45:29 CST 2017
     */
    public void setPrice_market(Double price_market) {
        this.price_market = price_market;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_product.price_site
     *
     * @return the value of ujn_product.price_site
     *
     * @mbg.generated Wed Mar 08 14:45:29 CST 2017
     */
    public Double getPrice_site() {
        return price_site;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_product.price_site
     *
     * @param price_site the value for ujn_product.price_site
     *
     * @mbg.generated Wed Mar 08 14:45:29 CST 2017
     */
    public void setPrice_site(Double price_site) {
        this.price_site = price_site;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_product.price_cost
     *
     * @return the value of ujn_product.price_cost
     *
     * @mbg.generated Wed Mar 08 14:45:29 CST 2017
     */
    public Double getPrice_cost() {
        return price_cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_product.price_cost
     *
     * @param price_cost the value for ujn_product.price_cost
     *
     * @mbg.generated Wed Mar 08 14:45:29 CST 2017
     */
    public void setPrice_cost(Double price_cost) {
        this.price_cost = price_cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_product.price_min
     *
     * @return the value of ujn_product.price_min
     *
     * @mbg.generated Wed Mar 08 14:45:29 CST 2017
     */
    public Double getPrice_min() {
        return price_min;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_product.price_min
     *
     * @param price_min the value for ujn_product.price_min
     *
     * @mbg.generated Wed Mar 08 14:45:29 CST 2017
     */
    public void setPrice_min(Double price_min) {
        this.price_min = price_min;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_product.units
     *
     * @return the value of ujn_product.units
     *
     * @mbg.generated Wed Mar 08 14:45:29 CST 2017
     */
    public String getUnits() {
        return units;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_product.units
     *
     * @param units the value for ujn_product.units
     *
     * @mbg.generated Wed Mar 08 14:45:29 CST 2017
     */
    public void setUnits(String units) {
        this.units = units == null ? null : units.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_product.description
     *
     * @return the value of ujn_product.description
     *
     * @mbg.generated Wed Mar 08 14:45:29 CST 2017
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_product.description
     *
     * @param description the value for ujn_product.description
     *
     * @mbg.generated Wed Mar 08 14:45:29 CST 2017
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_product.status
     *
     * @return the value of ujn_product.status
     *
     * @mbg.generated Wed Mar 08 14:45:29 CST 2017
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_product.status
     *
     * @param status the value for ujn_product.status
     *
     * @mbg.generated Wed Mar 08 14:45:29 CST 2017
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_product.create_date
     *
     * @return the value of ujn_product.create_date
     *
     * @mbg.generated Wed Mar 08 14:45:29 CST 2017
     */
    public String getCreate_date() {
        return create_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_product.create_date
     *
     * @param create_date the value for ujn_product.create_date
     *
     * @mbg.generated Wed Mar 08 14:45:29 CST 2017
     */
    public void setCreate_date(String create_date) {
        this.create_date = create_date == null ? null : create_date.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_product.keywords
     *
     * @return the value of ujn_product.keywords
     *
     * @mbg.generated Wed Mar 08 14:45:29 CST 2017
     */
    public String getKeywords() {
        return keywords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_product.keywords
     *
     * @param keywords the value for ujn_product.keywords
     *
     * @mbg.generated Wed Mar 08 14:45:29 CST 2017
     */
    public void setKeywords(String keywords) {
        this.keywords = keywords == null ? null : keywords.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_product.pic
     *
     * @return the value of ujn_product.pic
     *
     * @mbg.generated Wed Mar 08 14:45:29 CST 2017
     */
    public String getPic() {
        return pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_product.pic
     *
     * @param pic the value for ujn_product.pic
     *
     * @mbg.generated Wed Mar 08 14:45:29 CST 2017
     */
    public void setPic(String pic) {
        this.pic = pic == null ? null : pic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_product.type
     *
     * @return the value of ujn_product.type
     *
     * @mbg.generated Wed Mar 08 14:45:29 CST 2017
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_product.type
     *
     * @param type the value for ujn_product.type
     *
     * @mbg.generated Wed Mar 08 14:45:29 CST 2017
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

	public String getStatus_name() {
		return status_name;
	}

	public void setStatus_name(String status_name) {
		this.status_name = status_name;
	}

	public String getType_name() {
		return type_name;
	}

	public void setType_name(String type_name) {
		this.type_name = type_name;
	}

	public int getNo_order() {
		return no_order;
	}

	public void setNo_order(int no_order) {
		this.no_order = no_order;
	}

	public String getProduct_no() {
		return product_no;
	}

	public void setProduct_no(String product_no) {
		this.product_no = product_no;
	}

	public Integer getSales() {
		return sales;
	}

	public void setSales(Integer sales) {
		this.sales = sales;
	}

	public String getBig_type() {
		return big_type;
	}

	public void setBig_type(String big_type) {
		this.big_type = big_type;
	}

	public String getBig_type_name() {
		return big_type_name;
	}

	public void setBig_type_name(String big_type_name) {
		this.big_type_name = big_type_name;
	}
}