package framework.system.dao;

import java.util.List;

import framework.system.model.Code;

public interface CodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujn_code
     *
     * @mbg.generated Sun Jan 22 16:29:30 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujn_code
     *
     * @mbg.generated Sun Jan 22 16:29:30 CST 2017
     */
    int insert(Code record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujn_code
     *
     * @mbg.generated Sun Jan 22 16:29:30 CST 2017
     */
    int insertSelective(Code record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujn_code
     *
     * @mbg.generated Sun Jan 22 16:29:30 CST 2017
     */
    Code selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujn_code
     *
     * @mbg.generated Sun Jan 22 16:29:30 CST 2017
     */
    int updateByPrimaryKeySelective(Code record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujn_code
     *
     * @mbg.generated Sun Jan 22 16:29:30 CST 2017
     */
    int updateByPrimaryKey(Code record);

	Code queryCodeByLogin(Code codeParam);

	List<Code> queryCodeList(Code code);
}