package framework.system.dao;

import framework.system.model.DeptMain;

public interface DeptMainMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujn_dept_main
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujn_dept_main
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    int insert(DeptMain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujn_dept_main
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    int insertSelective(DeptMain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujn_dept_main
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    DeptMain selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujn_dept_main
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    int updateByPrimaryKeySelective(DeptMain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujn_dept_main
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    int updateByPrimaryKey(DeptMain record);
}