package framework.system.dao;

import framework.system.model.Education;

public interface EducationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujn_education
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujn_education
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    int insert(Education record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujn_education
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    int insertSelective(Education record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujn_education
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    Education selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujn_education
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    int updateByPrimaryKeySelective(Education record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujn_education
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    int updateByPrimaryKey(Education record);
}