package framework.system.dao;

import framework.system.model.Funcright;

public interface FuncrightMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujn_funcright
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujn_funcright
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    int insert(Funcright record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujn_funcright
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    int insertSelective(Funcright record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujn_funcright
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    Funcright selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujn_funcright
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    int updateByPrimaryKeySelective(Funcright record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujn_funcright
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    int updateByPrimaryKey(Funcright record);
}