package framework.system.dao;

import framework.system.model.FuncrightType;

public interface FuncrightTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujn_funcright_type
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujn_funcright_type
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    int insert(FuncrightType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujn_funcright_type
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    int insertSelective(FuncrightType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujn_funcright_type
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    FuncrightType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujn_funcright_type
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    int updateByPrimaryKeySelective(FuncrightType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujn_funcright_type
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    int updateByPrimaryKey(FuncrightType record);
}