package framework.system.dao;

import java.util.List;

import framework.system.model.Role;

public interface RoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujn_role
     *
     * @mbg.generated Mon Feb 13 22:47:30 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujn_role
     *
     * @mbg.generated Mon Feb 13 22:47:30 CST 2017
     */
    int insert(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujn_role
     *
     * @mbg.generated Mon Feb 13 22:47:30 CST 2017
     */
    int insertSelective(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujn_role
     *
     * @mbg.generated Mon Feb 13 22:47:30 CST 2017
     */
    Role selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujn_role
     *
     * @mbg.generated Mon Feb 13 22:47:30 CST 2017
     */
    int updateByPrimaryKeySelective(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujn_role
     *
     * @mbg.generated Mon Feb 13 22:47:30 CST 2017
     */
    int updateByPrimaryKey(Role record);
    
    /**
     * 
     * @Description: 角色分页列表 
     * @param role
     * @return
     */
	List<Role> queryRoleList(Role role);
	
	/**
	 * 
	 * @Description: 角色下拉列表 
	 * @return
	 */
	List<Role> getRoleSelectList();

	List<Role> queryRoleTree(Role role);
}