package framework.system.dao;

import framework.system.model.RoleDataright;

public interface RoleDatarightMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujn_role_dataright
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujn_role_dataright
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    int insert(RoleDataright record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujn_role_dataright
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    int insertSelective(RoleDataright record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujn_role_dataright
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    RoleDataright selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujn_role_dataright
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    int updateByPrimaryKeySelective(RoleDataright record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujn_role_dataright
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    int updateByPrimaryKey(RoleDataright record);
}