package framework.system.dao;

import java.util.List;

import framework.system.model.User;


public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujn_user
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujn_user
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujn_user
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujn_user
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    User selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujn_user
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujn_user
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    int updateByPrimaryKey(User record);
    
    /**
     * 
     * @Description: 登录用户查询 
     * @param userParam
     * @return
     */
	User queryUserByLogin(User userParam);
	
	/**
	 * 
	 * @Description: 用户分页查询 
	 * @param user
	 * @return
	 */
	List<User> queryUserList(User user);
}