package com.yuanyuansinian.dao.gift;

import java.util.List;
import java.util.Map;

import com.yuanyuansinian.model.gift.HallGift;

public interface HallGiftMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujn_hall_gift
     *
     * @mbg.generated Tue May 16 10:02:41 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujn_hall_gift
     *
     * @mbg.generated Tue May 16 10:02:41 CST 2017
     */
    int insert(HallGift record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujn_hall_gift
     *
     * @mbg.generated Tue May 16 10:02:41 CST 2017
     */
    int insertSelective(HallGift record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujn_hall_gift
     *
     * @mbg.generated Tue May 16 10:02:41 CST 2017
     */
    HallGift selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujn_hall_gift
     *
     * @mbg.generated Tue May 16 10:02:41 CST 2017
     */
    int updateByPrimaryKeySelective(HallGift record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujn_hall_gift
     *
     * @mbg.generated Tue May 16 10:02:41 CST 2017
     */
    int updateByPrimaryKey(HallGift record);

	List<HallGift> queryHallGiftListByType(String type);

	List<HallGift> queryHallGiftList(HallGift hallGift);

	List<HallGift> queryHallGiftListForHall(Map<String, Object> map);

}