package com.yuanyuansinian.dao.hall;

import java.util.List;
import java.util.Map;

import com.yuanyuansinian.model.hall.Hall;
import com.yuanyuansinian.model.hall.HallWithBLOBs;

public interface HallMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujn_hall
     *
     * @mbg.generated Fri Mar 10 16:01:30 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujn_hall
     *
     * @mbg.generated Fri Mar 10 16:01:30 CST 2017
     */
    int insert(HallWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujn_hall
     *
     * @mbg.generated Fri Mar 10 16:01:30 CST 2017
     */
    int insertSelective(HallWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujn_hall
     *
     * @mbg.generated Fri Mar 10 16:01:30 CST 2017
     */
    HallWithBLOBs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujn_hall
     *
     * @mbg.generated Fri Mar 10 16:01:30 CST 2017
     */
    int updateByPrimaryKeySelective(HallWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujn_hall
     *
     * @mbg.generated Fri Mar 10 16:01:30 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(HallWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujn_hall
     *
     * @mbg.generated Fri Mar 10 16:01:30 CST 2017
     */
    int updateByPrimaryKey(Hall record);

	List<Hall> queryHallListByType(Hall hall);

	List<Hall> queryHallListByMember(Map<String, Object> map);

	List<Hall> queryHallListByOpenType(String open_type);

	List<Hall> queryHallList(Hall hall);

	List<Hall> queryHallPageListByMemberHall(Hall hall);

	List<Hall> queryHallNewList(int countNum);

	List<Hall> queryHallListBySearch(String search_text);

	void uploadSingleHallImg(HallWithBLOBs hall);
}