package ujn.school.cn.dao.file;

import ujn.school.cn.model.file.File;

public interface FileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujn_file
     *
     * @mbg.generated Thu Aug 03 14:43:21 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujn_file
     *
     * @mbg.generated Thu Aug 03 14:43:21 CST 2017
     */
    int insert(File record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujn_file
     *
     * @mbg.generated Thu Aug 03 14:43:21 CST 2017
     */
    int insertSelective(File record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujn_file
     *
     * @mbg.generated Thu Aug 03 14:43:21 CST 2017
     */
    File selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujn_file
     *
     * @mbg.generated Thu Aug 03 14:43:21 CST 2017
     */
    int updateByPrimaryKeySelective(File record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujn_file
     *
     * @mbg.generated Thu Aug 03 14:43:21 CST 2017
     */
    int updateByPrimaryKey(File record);
}