package framework.system.model;

public class CodeType {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_code_type.Id
     *
     * @mbg.generated Thu Mar 16 11:09:56 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_code_type.code_type
     *
     * @mbg.generated Thu Mar 16 11:09:56 CST 2017
     */
    private String code_type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_code_type.system_type
     *
     * @mbg.generated Thu Mar 16 11:09:56 CST 2017
     */
    private String system_type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_code_type.type_name
     *
     * @mbg.generated Thu Mar 16 11:09:56 CST 2017
     */
    private String type_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_code_type.order_num
     *
     * @mbg.generated Thu Mar 16 11:09:56 CST 2017
     */
    private String order_num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_code_type.is_edit
     *
     * @mbg.generated Thu Mar 16 11:09:56 CST 2017
     */
    private String is_edit;
    private String is_edit_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_code_type.is_memory
     *
     * @mbg.generated Thu Mar 16 11:09:56 CST 2017
     */
    private String is_memory;
    private String is_memory_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_code_type.remark
     *
     * @mbg.generated Thu Mar 16 11:09:56 CST 2017
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_code_type.Id
     *
     * @return the value of ujn_code_type.Id
     *
     * @mbg.generated Thu Mar 16 11:09:56 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_code_type.Id
     *
     * @param id the value for ujn_code_type.Id
     *
     * @mbg.generated Thu Mar 16 11:09:56 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_code_type.code_type
     *
     * @return the value of ujn_code_type.code_type
     *
     * @mbg.generated Thu Mar 16 11:09:56 CST 2017
     */
    public String getCode_type() {
        return code_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_code_type.code_type
     *
     * @param code_type the value for ujn_code_type.code_type
     *
     * @mbg.generated Thu Mar 16 11:09:56 CST 2017
     */
    public void setCode_type(String code_type) {
        this.code_type = code_type == null ? null : code_type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_code_type.system_type
     *
     * @return the value of ujn_code_type.system_type
     *
     * @mbg.generated Thu Mar 16 11:09:56 CST 2017
     */
    public String getSystem_type() {
        return system_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_code_type.system_type
     *
     * @param system_type the value for ujn_code_type.system_type
     *
     * @mbg.generated Thu Mar 16 11:09:56 CST 2017
     */
    public void setSystem_type(String system_type) {
        this.system_type = system_type == null ? null : system_type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_code_type.type_name
     *
     * @return the value of ujn_code_type.type_name
     *
     * @mbg.generated Thu Mar 16 11:09:56 CST 2017
     */
    public String getType_name() {
        return type_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_code_type.type_name
     *
     * @param type_name the value for ujn_code_type.type_name
     *
     * @mbg.generated Thu Mar 16 11:09:56 CST 2017
     */
    public void setType_name(String type_name) {
        this.type_name = type_name == null ? null : type_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_code_type.order_num
     *
     * @return the value of ujn_code_type.order_num
     *
     * @mbg.generated Thu Mar 16 11:09:56 CST 2017
     */
    public String getOrder_num() {
        return order_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_code_type.order_num
     *
     * @param order_num the value for ujn_code_type.order_num
     *
     * @mbg.generated Thu Mar 16 11:09:56 CST 2017
     */
    public void setOrder_num(String order_num) {
        this.order_num = order_num == null ? null : order_num.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_code_type.is_edit
     *
     * @return the value of ujn_code_type.is_edit
     *
     * @mbg.generated Thu Mar 16 11:09:56 CST 2017
     */
    public String getIs_edit() {
        return is_edit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_code_type.is_edit
     *
     * @param is_edit the value for ujn_code_type.is_edit
     *
     * @mbg.generated Thu Mar 16 11:09:56 CST 2017
     */
    public void setIs_edit(String is_edit) {
        this.is_edit = is_edit == null ? null : is_edit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_code_type.is_memory
     *
     * @return the value of ujn_code_type.is_memory
     *
     * @mbg.generated Thu Mar 16 11:09:56 CST 2017
     */
    public String getIs_memory() {
        return is_memory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_code_type.is_memory
     *
     * @param is_memory the value for ujn_code_type.is_memory
     *
     * @mbg.generated Thu Mar 16 11:09:56 CST 2017
     */
    public void setIs_memory(String is_memory) {
        this.is_memory = is_memory == null ? null : is_memory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_code_type.remark
     *
     * @return the value of ujn_code_type.remark
     *
     * @mbg.generated Thu Mar 16 11:09:56 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_code_type.remark
     *
     * @param remark the value for ujn_code_type.remark
     *
     * @mbg.generated Thu Mar 16 11:09:56 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

	public String getIs_edit_name() {
		return is_edit_name;
	}

	public void setIs_edit_name(String is_edit_name) {
		this.is_edit_name = is_edit_name;
	}

	public String getIs_memory_name() {
		return is_memory_name;
	}

	public void setIs_memory_name(String is_memory_name) {
		this.is_memory_name = is_memory_name;
	}
}