package framework.system.model;

public class Code {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_code.Id
     *
     * @mbg.generated Thu Mar 16 15:45:12 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_code.code_type
     *
     * @mbg.generated Thu Mar 16 15:45:12 CST 2017
     */
    private String code_type;
    private String code_type_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_code.code_value
     *
     * @mbg.generated Thu Mar 16 15:45:12 CST 2017
     */
    private String code_value;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_code.code_name
     *
     * @mbg.generated Thu Mar 16 15:45:12 CST 2017
     */
    private String code_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_code.order_num
     *
     * @mbg.generated Thu Mar 16 15:45:12 CST 2017
     */
    private String order_num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_code.status
     *
     * @mbg.generated Thu Mar 16 15:45:12 CST 2017
     */
    private String status;
    private String status_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_code.remark
     *
     * @mbg.generated Thu Mar 16 15:45:12 CST 2017
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_code.Id
     *
     * @return the value of ujn_code.Id
     *
     * @mbg.generated Thu Mar 16 15:45:12 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_code.Id
     *
     * @param id the value for ujn_code.Id
     *
     * @mbg.generated Thu Mar 16 15:45:12 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_code.code_type
     *
     * @return the value of ujn_code.code_type
     *
     * @mbg.generated Thu Mar 16 15:45:12 CST 2017
     */
    public String getCode_type() {
        return code_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_code.code_type
     *
     * @param code_type the value for ujn_code.code_type
     *
     * @mbg.generated Thu Mar 16 15:45:12 CST 2017
     */
    public void setCode_type(String code_type) {
        this.code_type = code_type == null ? null : code_type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_code.code_value
     *
     * @return the value of ujn_code.code_value
     *
     * @mbg.generated Thu Mar 16 15:45:12 CST 2017
     */
    public String getCode_value() {
        return code_value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_code.code_value
     *
     * @param code_value the value for ujn_code.code_value
     *
     * @mbg.generated Thu Mar 16 15:45:12 CST 2017
     */
    public void setCode_value(String code_value) {
        this.code_value = code_value == null ? null : code_value.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_code.code_name
     *
     * @return the value of ujn_code.code_name
     *
     * @mbg.generated Thu Mar 16 15:45:12 CST 2017
     */
    public String getCode_name() {
        return code_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_code.code_name
     *
     * @param code_name the value for ujn_code.code_name
     *
     * @mbg.generated Thu Mar 16 15:45:12 CST 2017
     */
    public void setCode_name(String code_name) {
        this.code_name = code_name == null ? null : code_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_code.order_num
     *
     * @return the value of ujn_code.order_num
     *
     * @mbg.generated Thu Mar 16 15:45:12 CST 2017
     */
    public String getOrder_num() {
        return order_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_code.order_num
     *
     * @param order_num the value for ujn_code.order_num
     *
     * @mbg.generated Thu Mar 16 15:45:12 CST 2017
     */
    public void setOrder_num(String order_num) {
        this.order_num = order_num == null ? null : order_num.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_code.status
     *
     * @return the value of ujn_code.status
     *
     * @mbg.generated Thu Mar 16 15:45:12 CST 2017
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_code.status
     *
     * @param status the value for ujn_code.status
     *
     * @mbg.generated Thu Mar 16 15:45:12 CST 2017
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_code.remark
     *
     * @return the value of ujn_code.remark
     *
     * @mbg.generated Thu Mar 16 15:45:12 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_code.remark
     *
     * @param remark the value for ujn_code.remark
     *
     * @mbg.generated Thu Mar 16 15:45:12 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

	public String getCode_type_name() {
		return code_type_name;
	}

	public void setCode_type_name(String code_type_name) {
		this.code_type_name = code_type_name;
	}

	public String getStatus_name() {
		return status_name;
	}

	public void setStatus_name(String status_name) {
		this.status_name = status_name;
	}
}