package framework.system.model;

public class Code {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_code.Id
     *
     * @mbg.generated Sun Jan 22 16:29:30 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_code.code_type
     *
     * @mbg.generated Sun Jan 22 16:29:30 CST 2017
     */
    private String code_type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_code.code
     *
     * @mbg.generated Sun Jan 22 16:29:30 CST 2017
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_code.explain
     *
     * @mbg.generated Sun Jan 22 16:29:30 CST 2017
     */
    private String explain;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_code.order_num
     *
     * @mbg.generated Sun Jan 22 16:29:30 CST 2017
     */
    private String order_num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_code.status
     *
     * @mbg.generated Sun Jan 22 16:29:30 CST 2017
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_code.remark
     *
     * @mbg.generated Sun Jan 22 16:29:30 CST 2017
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_code.Id
     *
     * @return the value of ujn_code.Id
     *
     * @mbg.generated Sun Jan 22 16:29:30 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_code.Id
     *
     * @param id the value for ujn_code.Id
     *
     * @mbg.generated Sun Jan 22 16:29:30 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_code.code_type
     *
     * @return the value of ujn_code.code_type
     *
     * @mbg.generated Sun Jan 22 16:29:30 CST 2017
     */
    public String getCode_type() {
        return code_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_code.code_type
     *
     * @param code_type the value for ujn_code.code_type
     *
     * @mbg.generated Sun Jan 22 16:29:30 CST 2017
     */
    public void setCode_type(String code_type) {
        this.code_type = code_type == null ? null : code_type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_code.code
     *
     * @return the value of ujn_code.code
     *
     * @mbg.generated Sun Jan 22 16:29:30 CST 2017
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_code.code
     *
     * @param code the value for ujn_code.code
     *
     * @mbg.generated Sun Jan 22 16:29:30 CST 2017
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_code.explain
     *
     * @return the value of ujn_code.explain
     *
     * @mbg.generated Sun Jan 22 16:29:30 CST 2017
     */
    public String getExplain() {
        return explain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_code.explain
     *
     * @param explain the value for ujn_code.explain
     *
     * @mbg.generated Sun Jan 22 16:29:30 CST 2017
     */
    public void setExplain(String explain) {
        this.explain = explain == null ? null : explain.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_code.order_num
     *
     * @return the value of ujn_code.order_num
     *
     * @mbg.generated Sun Jan 22 16:29:30 CST 2017
     */
    public String getOrder_num() {
        return order_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_code.order_num
     *
     * @param order_num the value for ujn_code.order_num
     *
     * @mbg.generated Sun Jan 22 16:29:30 CST 2017
     */
    public void setOrder_num(String order_num) {
        this.order_num = order_num == null ? null : order_num.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_code.status
     *
     * @return the value of ujn_code.status
     *
     * @mbg.generated Sun Jan 22 16:29:30 CST 2017
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_code.status
     *
     * @param status the value for ujn_code.status
     *
     * @mbg.generated Sun Jan 22 16:29:30 CST 2017
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_code.remark
     *
     * @return the value of ujn_code.remark
     *
     * @mbg.generated Sun Jan 22 16:29:30 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_code.remark
     *
     * @param remark the value for ujn_code.remark
     *
     * @mbg.generated Sun Jan 22 16:29:30 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}