package framework.system.model;

public class Department {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_department.Id
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_department.dept_code
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    private String dept_code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_department.dept_name
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    private String dept_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_department.dept_main
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    private String dept_main;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_department.parent_code
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    private String parent_code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_department.admin_divison
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    private String admin_divison;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_department.dept_level
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    private String dept_level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_department.manager_user_id
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    private String manager_user_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_department.contact_tel
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    private String contact_tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_department.contact_fax
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    private String contact_fax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_department.contact_addr
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    private String contact_addr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_department.contact_zip
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    private String contact_zip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_department.remark
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_department.valid_flag
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    private String valid_flag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_department.create_date
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    private String create_date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_department.create_user_id
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    private String create_user_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_department.update_date
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    private String update_date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_department.update_user_id
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    private String update_user_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_department.Id
     *
     * @return the value of ujn_department.Id
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_department.Id
     *
     * @param id the value for ujn_department.Id
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_department.dept_code
     *
     * @return the value of ujn_department.dept_code
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public String getDept_code() {
        return dept_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_department.dept_code
     *
     * @param dept_code the value for ujn_department.dept_code
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public void setDept_code(String dept_code) {
        this.dept_code = dept_code == null ? null : dept_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_department.dept_name
     *
     * @return the value of ujn_department.dept_name
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public String getDept_name() {
        return dept_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_department.dept_name
     *
     * @param dept_name the value for ujn_department.dept_name
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public void setDept_name(String dept_name) {
        this.dept_name = dept_name == null ? null : dept_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_department.dept_main
     *
     * @return the value of ujn_department.dept_main
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public String getDept_main() {
        return dept_main;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_department.dept_main
     *
     * @param dept_main the value for ujn_department.dept_main
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public void setDept_main(String dept_main) {
        this.dept_main = dept_main == null ? null : dept_main.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_department.parent_code
     *
     * @return the value of ujn_department.parent_code
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public String getParent_code() {
        return parent_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_department.parent_code
     *
     * @param parent_code the value for ujn_department.parent_code
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public void setParent_code(String parent_code) {
        this.parent_code = parent_code == null ? null : parent_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_department.admin_divison
     *
     * @return the value of ujn_department.admin_divison
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public String getAdmin_divison() {
        return admin_divison;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_department.admin_divison
     *
     * @param admin_divison the value for ujn_department.admin_divison
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public void setAdmin_divison(String admin_divison) {
        this.admin_divison = admin_divison == null ? null : admin_divison.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_department.dept_level
     *
     * @return the value of ujn_department.dept_level
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public String getDept_level() {
        return dept_level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_department.dept_level
     *
     * @param dept_level the value for ujn_department.dept_level
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public void setDept_level(String dept_level) {
        this.dept_level = dept_level == null ? null : dept_level.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_department.manager_user_id
     *
     * @return the value of ujn_department.manager_user_id
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public String getManager_user_id() {
        return manager_user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_department.manager_user_id
     *
     * @param manager_user_id the value for ujn_department.manager_user_id
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public void setManager_user_id(String manager_user_id) {
        this.manager_user_id = manager_user_id == null ? null : manager_user_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_department.contact_tel
     *
     * @return the value of ujn_department.contact_tel
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public String getContact_tel() {
        return contact_tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_department.contact_tel
     *
     * @param contact_tel the value for ujn_department.contact_tel
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public void setContact_tel(String contact_tel) {
        this.contact_tel = contact_tel == null ? null : contact_tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_department.contact_fax
     *
     * @return the value of ujn_department.contact_fax
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public String getContact_fax() {
        return contact_fax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_department.contact_fax
     *
     * @param contact_fax the value for ujn_department.contact_fax
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public void setContact_fax(String contact_fax) {
        this.contact_fax = contact_fax == null ? null : contact_fax.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_department.contact_addr
     *
     * @return the value of ujn_department.contact_addr
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public String getContact_addr() {
        return contact_addr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_department.contact_addr
     *
     * @param contact_addr the value for ujn_department.contact_addr
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public void setContact_addr(String contact_addr) {
        this.contact_addr = contact_addr == null ? null : contact_addr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_department.contact_zip
     *
     * @return the value of ujn_department.contact_zip
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public String getContact_zip() {
        return contact_zip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_department.contact_zip
     *
     * @param contact_zip the value for ujn_department.contact_zip
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public void setContact_zip(String contact_zip) {
        this.contact_zip = contact_zip == null ? null : contact_zip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_department.remark
     *
     * @return the value of ujn_department.remark
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_department.remark
     *
     * @param remark the value for ujn_department.remark
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_department.valid_flag
     *
     * @return the value of ujn_department.valid_flag
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public String getValid_flag() {
        return valid_flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_department.valid_flag
     *
     * @param valid_flag the value for ujn_department.valid_flag
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public void setValid_flag(String valid_flag) {
        this.valid_flag = valid_flag == null ? null : valid_flag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_department.create_date
     *
     * @return the value of ujn_department.create_date
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public String getCreate_date() {
        return create_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_department.create_date
     *
     * @param create_date the value for ujn_department.create_date
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public void setCreate_date(String create_date) {
        this.create_date = create_date == null ? null : create_date.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_department.create_user_id
     *
     * @return the value of ujn_department.create_user_id
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public String getCreate_user_id() {
        return create_user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_department.create_user_id
     *
     * @param create_user_id the value for ujn_department.create_user_id
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public void setCreate_user_id(String create_user_id) {
        this.create_user_id = create_user_id == null ? null : create_user_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_department.update_date
     *
     * @return the value of ujn_department.update_date
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public String getUpdate_date() {
        return update_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_department.update_date
     *
     * @param update_date the value for ujn_department.update_date
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public void setUpdate_date(String update_date) {
        this.update_date = update_date == null ? null : update_date.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_department.update_user_id
     *
     * @return the value of ujn_department.update_user_id
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public String getUpdate_user_id() {
        return update_user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_department.update_user_id
     *
     * @param update_user_id the value for ujn_department.update_user_id
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public void setUpdate_user_id(String update_user_id) {
        this.update_user_id = update_user_id == null ? null : update_user_id.trim();
    }
}