package framework.system.model;

public class DeptLevel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_dept_level.Id
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_dept_level.level_code
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    private String level_code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_dept_level.level_name
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    private String level_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_dept_level.status
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_dept_level.Id
     *
     * @return the value of ujn_dept_level.Id
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_dept_level.Id
     *
     * @param id the value for ujn_dept_level.Id
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_dept_level.level_code
     *
     * @return the value of ujn_dept_level.level_code
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public String getLevel_code() {
        return level_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_dept_level.level_code
     *
     * @param level_code the value for ujn_dept_level.level_code
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public void setLevel_code(String level_code) {
        this.level_code = level_code == null ? null : level_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_dept_level.level_name
     *
     * @return the value of ujn_dept_level.level_name
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public String getLevel_name() {
        return level_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_dept_level.level_name
     *
     * @param level_name the value for ujn_dept_level.level_name
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public void setLevel_name(String level_name) {
        this.level_name = level_name == null ? null : level_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_dept_level.status
     *
     * @return the value of ujn_dept_level.status
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_dept_level.status
     *
     * @param status the value for ujn_dept_level.status
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
}