package framework.system.model;

import java.util.Date;

public class Funcright {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_funcright.Id
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_funcright.funcright_code
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    private String funcright_code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_funcright.funcright_name
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    private String funcright_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_funcright.funcright_type_code
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    private String funcright_type_code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_funcright.url
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_funcright.icon
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    private String icon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_funcright.icon_open
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    private String icon_open;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_funcright.icon_close
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    private String icon_close;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_funcright.show_order
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    private String show_order;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_funcright.parent_code
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    private String parent_code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_funcright.remark
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_funcright.status
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_funcright.link
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    private String link;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_funcright.create_date
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    private Date create_date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_funcright.create_user_id
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    private String create_user_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_funcright.update_date
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    private Date update_date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_funcright.update_user_id
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    private String update_user_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_funcright.Id
     *
     * @return the value of ujn_funcright.Id
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_funcright.Id
     *
     * @param id the value for ujn_funcright.Id
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_funcright.funcright_code
     *
     * @return the value of ujn_funcright.funcright_code
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public String getFuncright_code() {
        return funcright_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_funcright.funcright_code
     *
     * @param funcright_code the value for ujn_funcright.funcright_code
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public void setFuncright_code(String funcright_code) {
        this.funcright_code = funcright_code == null ? null : funcright_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_funcright.funcright_name
     *
     * @return the value of ujn_funcright.funcright_name
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public String getFuncright_name() {
        return funcright_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_funcright.funcright_name
     *
     * @param funcright_name the value for ujn_funcright.funcright_name
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public void setFuncright_name(String funcright_name) {
        this.funcright_name = funcright_name == null ? null : funcright_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_funcright.funcright_type_code
     *
     * @return the value of ujn_funcright.funcright_type_code
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public String getFuncright_type_code() {
        return funcright_type_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_funcright.funcright_type_code
     *
     * @param funcright_type_code the value for ujn_funcright.funcright_type_code
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public void setFuncright_type_code(String funcright_type_code) {
        this.funcright_type_code = funcright_type_code == null ? null : funcright_type_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_funcright.url
     *
     * @return the value of ujn_funcright.url
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_funcright.url
     *
     * @param url the value for ujn_funcright.url
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_funcright.icon
     *
     * @return the value of ujn_funcright.icon
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_funcright.icon
     *
     * @param icon the value for ujn_funcright.icon
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public void setIcon(String icon) {
        this.icon = icon == null ? null : icon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_funcright.icon_open
     *
     * @return the value of ujn_funcright.icon_open
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public String getIcon_open() {
        return icon_open;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_funcright.icon_open
     *
     * @param icon_open the value for ujn_funcright.icon_open
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public void setIcon_open(String icon_open) {
        this.icon_open = icon_open == null ? null : icon_open.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_funcright.icon_close
     *
     * @return the value of ujn_funcright.icon_close
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public String getIcon_close() {
        return icon_close;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_funcright.icon_close
     *
     * @param icon_close the value for ujn_funcright.icon_close
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public void setIcon_close(String icon_close) {
        this.icon_close = icon_close == null ? null : icon_close.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_funcright.show_order
     *
     * @return the value of ujn_funcright.show_order
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public String getShow_order() {
        return show_order;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_funcright.show_order
     *
     * @param show_order the value for ujn_funcright.show_order
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public void setShow_order(String show_order) {
        this.show_order = show_order == null ? null : show_order.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_funcright.parent_code
     *
     * @return the value of ujn_funcright.parent_code
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public String getParent_code() {
        return parent_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_funcright.parent_code
     *
     * @param parent_code the value for ujn_funcright.parent_code
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public void setParent_code(String parent_code) {
        this.parent_code = parent_code == null ? null : parent_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_funcright.remark
     *
     * @return the value of ujn_funcright.remark
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_funcright.remark
     *
     * @param remark the value for ujn_funcright.remark
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_funcright.status
     *
     * @return the value of ujn_funcright.status
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_funcright.status
     *
     * @param status the value for ujn_funcright.status
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_funcright.link
     *
     * @return the value of ujn_funcright.link
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public String getLink() {
        return link;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_funcright.link
     *
     * @param link the value for ujn_funcright.link
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public void setLink(String link) {
        this.link = link == null ? null : link.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_funcright.create_date
     *
     * @return the value of ujn_funcright.create_date
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public Date getCreate_date() {
        return create_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_funcright.create_date
     *
     * @param create_date the value for ujn_funcright.create_date
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public void setCreate_date(Date create_date) {
        this.create_date = create_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_funcright.create_user_id
     *
     * @return the value of ujn_funcright.create_user_id
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public String getCreate_user_id() {
        return create_user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_funcright.create_user_id
     *
     * @param create_user_id the value for ujn_funcright.create_user_id
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public void setCreate_user_id(String create_user_id) {
        this.create_user_id = create_user_id == null ? null : create_user_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_funcright.update_date
     *
     * @return the value of ujn_funcright.update_date
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public Date getUpdate_date() {
        return update_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_funcright.update_date
     *
     * @param update_date the value for ujn_funcright.update_date
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public void setUpdate_date(Date update_date) {
        this.update_date = update_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_funcright.update_user_id
     *
     * @return the value of ujn_funcright.update_user_id
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public String getUpdate_user_id() {
        return update_user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_funcright.update_user_id
     *
     * @param update_user_id the value for ujn_funcright.update_user_id
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public void setUpdate_user_id(String update_user_id) {
        this.update_user_id = update_user_id == null ? null : update_user_id.trim();
    }
}