package framework.system.model;

public class Position {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_position.Id
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_position.position_code
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    private String position_code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_position.position_name
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    private String position_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_position.status
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_position.Id
     *
     * @return the value of ujn_position.Id
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_position.Id
     *
     * @param id the value for ujn_position.Id
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_position.position_code
     *
     * @return the value of ujn_position.position_code
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public String getPosition_code() {
        return position_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_position.position_code
     *
     * @param position_code the value for ujn_position.position_code
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public void setPosition_code(String position_code) {
        this.position_code = position_code == null ? null : position_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_position.position_name
     *
     * @return the value of ujn_position.position_name
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public String getPosition_name() {
        return position_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_position.position_name
     *
     * @param position_name the value for ujn_position.position_name
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public void setPosition_name(String position_name) {
        this.position_name = position_name == null ? null : position_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_position.status
     *
     * @return the value of ujn_position.status
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_position.status
     *
     * @param status the value for ujn_position.status
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
}