package framework.system.model;

public class Role {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_role.Id
     *
     * @mbg.generated Mon Feb 13 22:47:30 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_role.role_code
     *
     * @mbg.generated Mon Feb 13 22:47:30 CST 2017
     */
    private String role_code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_role.role_name
     *
     * @mbg.generated Mon Feb 13 22:47:30 CST 2017
     */
    private String role_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_role.role_type_code
     *
     * @mbg.generated Mon Feb 13 22:47:30 CST 2017
     */
    private String role_type_code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_role.dept_code
     *
     * @mbg.generated Mon Feb 13 22:47:30 CST 2017
     */
    private String dept_code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_role.remark
     *
     * @mbg.generated Mon Feb 13 22:47:30 CST 2017
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_role.status
     *
     * @mbg.generated Mon Feb 13 22:47:30 CST 2017
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_role.Id
     *
     * @return the value of ujn_role.Id
     *
     * @mbg.generated Mon Feb 13 22:47:30 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_role.Id
     *
     * @param id the value for ujn_role.Id
     *
     * @mbg.generated Mon Feb 13 22:47:30 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_role.role_code
     *
     * @return the value of ujn_role.role_code
     *
     * @mbg.generated Mon Feb 13 22:47:30 CST 2017
     */
    public String getRole_code() {
        return role_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_role.role_code
     *
     * @param role_code the value for ujn_role.role_code
     *
     * @mbg.generated Mon Feb 13 22:47:30 CST 2017
     */
    public void setRole_code(String role_code) {
        this.role_code = role_code == null ? null : role_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_role.role_name
     *
     * @return the value of ujn_role.role_name
     *
     * @mbg.generated Mon Feb 13 22:47:30 CST 2017
     */
    public String getRole_name() {
        return role_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_role.role_name
     *
     * @param role_name the value for ujn_role.role_name
     *
     * @mbg.generated Mon Feb 13 22:47:30 CST 2017
     */
    public void setRole_name(String role_name) {
        this.role_name = role_name == null ? null : role_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_role.role_type_code
     *
     * @return the value of ujn_role.role_type_code
     *
     * @mbg.generated Mon Feb 13 22:47:30 CST 2017
     */
    public String getRole_type_code() {
        return role_type_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_role.role_type_code
     *
     * @param role_type_code the value for ujn_role.role_type_code
     *
     * @mbg.generated Mon Feb 13 22:47:30 CST 2017
     */
    public void setRole_type_code(String role_type_code) {
        this.role_type_code = role_type_code == null ? null : role_type_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_role.dept_code
     *
     * @return the value of ujn_role.dept_code
     *
     * @mbg.generated Mon Feb 13 22:47:30 CST 2017
     */
    public String getDept_code() {
        return dept_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_role.dept_code
     *
     * @param dept_code the value for ujn_role.dept_code
     *
     * @mbg.generated Mon Feb 13 22:47:30 CST 2017
     */
    public void setDept_code(String dept_code) {
        this.dept_code = dept_code == null ? null : dept_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_role.remark
     *
     * @return the value of ujn_role.remark
     *
     * @mbg.generated Mon Feb 13 22:47:30 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_role.remark
     *
     * @param remark the value for ujn_role.remark
     *
     * @mbg.generated Mon Feb 13 22:47:30 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_role.status
     *
     * @return the value of ujn_role.status
     *
     * @mbg.generated Mon Feb 13 22:47:30 CST 2017
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_role.status
     *
     * @param status the value for ujn_role.status
     *
     * @mbg.generated Mon Feb 13 22:47:30 CST 2017
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
}