package framework.system.model;

public class RoleType {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_role_type.Id
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_role_type.role_type_code
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    private String role_type_code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_role_type.role_type_name
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    private String role_type_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_role_type.remark
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_role_type.status
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_role_type.Id
     *
     * @return the value of ujn_role_type.Id
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_role_type.Id
     *
     * @param id the value for ujn_role_type.Id
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_role_type.role_type_code
     *
     * @return the value of ujn_role_type.role_type_code
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public String getRole_type_code() {
        return role_type_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_role_type.role_type_code
     *
     * @param role_type_code the value for ujn_role_type.role_type_code
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public void setRole_type_code(String role_type_code) {
        this.role_type_code = role_type_code == null ? null : role_type_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_role_type.role_type_name
     *
     * @return the value of ujn_role_type.role_type_name
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public String getRole_type_name() {
        return role_type_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_role_type.role_type_name
     *
     * @param role_type_name the value for ujn_role_type.role_type_name
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public void setRole_type_name(String role_type_name) {
        this.role_type_name = role_type_name == null ? null : role_type_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_role_type.remark
     *
     * @return the value of ujn_role_type.remark
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_role_type.remark
     *
     * @param remark the value for ujn_role_type.remark
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_role_type.status
     *
     * @return the value of ujn_role_type.status
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_role_type.status
     *
     * @param status the value for ujn_role_type.status
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
}