package framework.system.model;

public class RoleDataright {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_role_dataright.Id
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_role_dataright.role_code
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    private String role_code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_role_dataright.admin_division
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    private String admin_division;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_role_dataright.status
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_role_dataright.Id
     *
     * @return the value of ujn_role_dataright.Id
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_role_dataright.Id
     *
     * @param id the value for ujn_role_dataright.Id
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_role_dataright.role_code
     *
     * @return the value of ujn_role_dataright.role_code
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public String getRole_code() {
        return role_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_role_dataright.role_code
     *
     * @param role_code the value for ujn_role_dataright.role_code
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public void setRole_code(String role_code) {
        this.role_code = role_code == null ? null : role_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_role_dataright.admin_division
     *
     * @return the value of ujn_role_dataright.admin_division
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public String getAdmin_division() {
        return admin_division;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_role_dataright.admin_division
     *
     * @param admin_division the value for ujn_role_dataright.admin_division
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public void setAdmin_division(String admin_division) {
        this.admin_division = admin_division == null ? null : admin_division.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_role_dataright.status
     *
     * @return the value of ujn_role_dataright.status
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_role_dataright.status
     *
     * @param status the value for ujn_role_dataright.status
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
}