package framework.system.model;

import java.util.Date;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_user.Id
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_user.login_name
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    private String login_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_user.password
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_user.real_name
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    private String real_name;
    
    
    private String dept;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_user.position
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    private String position;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_user.user_type
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    private String user_type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_user.sex
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_user.pid
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    private String pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_user.birthday
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    private String birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_user.email
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_user.contact_tel
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    private String contact_tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_user.contact_mobile
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    private String contact_mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_user.contact_fax
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    private String contact_fax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_user.contact_zip
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    private String contact_zip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_user.contact_addr
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    private String contact_addr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_user.status
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    private String status;
    private String status_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_user.education
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    private String education;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_user.nation
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    private String nation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_user.political
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    private String political;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_user.remark
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_user.create_date
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    private Date create_date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_user.create_user_id
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    private String create_user_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_user.update_date
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    private Date update_date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_user.update_user_id
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    private String update_user_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_user.Id
     *
     * @return the value of ujn_user.Id
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_user.Id
     *
     * @param id the value for ujn_user.Id
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_user.login_name
     *
     * @return the value of ujn_user.login_name
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public String getLogin_name() {
        return login_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_user.login_name
     *
     * @param login_name the value for ujn_user.login_name
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public void setLogin_name(String login_name) {
        this.login_name = login_name == null ? null : login_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_user.password
     *
     * @return the value of ujn_user.password
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_user.password
     *
     * @param password the value for ujn_user.password
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_user.real_name
     *
     * @return the value of ujn_user.real_name
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public String getReal_name() {
        return real_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_user.real_name
     *
     * @param real_name the value for ujn_user.real_name
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public void setReal_name(String real_name) {
        this.real_name = real_name == null ? null : real_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_user.position
     *
     * @return the value of ujn_user.position
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_user.position
     *
     * @param position the value for ujn_user.position
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public void setPosition(String position) {
        this.position = position == null ? null : position.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_user.user_type
     *
     * @return the value of ujn_user.user_type
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public String getUser_type() {
        return user_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_user.user_type
     *
     * @param user_type the value for ujn_user.user_type
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public void setUser_type(String user_type) {
        this.user_type = user_type == null ? null : user_type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_user.sex
     *
     * @return the value of ujn_user.sex
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_user.sex
     *
     * @param sex the value for ujn_user.sex
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_user.pid
     *
     * @return the value of ujn_user.pid
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public String getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_user.pid
     *
     * @param pid the value for ujn_user.pid
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public void setPid(String pid) {
        this.pid = pid == null ? null : pid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_user.birthday
     *
     * @return the value of ujn_user.birthday
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public String getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_user.birthday
     *
     * @param birthday the value for ujn_user.birthday
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public void setBirthday(String birthday) {
        this.birthday = birthday == null ? null : birthday.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_user.email
     *
     * @return the value of ujn_user.email
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_user.email
     *
     * @param email the value for ujn_user.email
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_user.contact_tel
     *
     * @return the value of ujn_user.contact_tel
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public String getContact_tel() {
        return contact_tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_user.contact_tel
     *
     * @param contact_tel the value for ujn_user.contact_tel
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public void setContact_tel(String contact_tel) {
        this.contact_tel = contact_tel == null ? null : contact_tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_user.contact_mobile
     *
     * @return the value of ujn_user.contact_mobile
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public String getContact_mobile() {
        return contact_mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_user.contact_mobile
     *
     * @param contact_mobile the value for ujn_user.contact_mobile
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public void setContact_mobile(String contact_mobile) {
        this.contact_mobile = contact_mobile == null ? null : contact_mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_user.contact_fax
     *
     * @return the value of ujn_user.contact_fax
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public String getContact_fax() {
        return contact_fax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_user.contact_fax
     *
     * @param contact_fax the value for ujn_user.contact_fax
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public void setContact_fax(String contact_fax) {
        this.contact_fax = contact_fax == null ? null : contact_fax.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_user.contact_zip
     *
     * @return the value of ujn_user.contact_zip
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public String getContact_zip() {
        return contact_zip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_user.contact_zip
     *
     * @param contact_zip the value for ujn_user.contact_zip
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public void setContact_zip(String contact_zip) {
        this.contact_zip = contact_zip == null ? null : contact_zip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_user.contact_addr
     *
     * @return the value of ujn_user.contact_addr
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public String getContact_addr() {
        return contact_addr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_user.contact_addr
     *
     * @param contact_addr the value for ujn_user.contact_addr
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public void setContact_addr(String contact_addr) {
        this.contact_addr = contact_addr == null ? null : contact_addr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_user.status
     *
     * @return the value of ujn_user.status
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_user.status
     *
     * @param status the value for ujn_user.status
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_user.education
     *
     * @return the value of ujn_user.education
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public String getEducation() {
        return education;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_user.education
     *
     * @param education the value for ujn_user.education
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public void setEducation(String education) {
        this.education = education == null ? null : education.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_user.nation
     *
     * @return the value of ujn_user.nation
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public String getNation() {
        return nation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_user.nation
     *
     * @param nation the value for ujn_user.nation
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public void setNation(String nation) {
        this.nation = nation == null ? null : nation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_user.political
     *
     * @return the value of ujn_user.political
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public String getPolitical() {
        return political;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_user.political
     *
     * @param political the value for ujn_user.political
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public void setPolitical(String political) {
        this.political = political == null ? null : political.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_user.remark
     *
     * @return the value of ujn_user.remark
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_user.remark
     *
     * @param remark the value for ujn_user.remark
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_user.create_date
     *
     * @return the value of ujn_user.create_date
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public Date getCreate_date() {
        return create_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_user.create_date
     *
     * @param create_date the value for ujn_user.create_date
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public void setCreate_date(Date create_date) {
        this.create_date = create_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_user.create_user_id
     *
     * @return the value of ujn_user.create_user_id
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public String getCreate_user_id() {
        return create_user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_user.create_user_id
     *
     * @param create_user_id the value for ujn_user.create_user_id
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public void setCreate_user_id(String create_user_id) {
        this.create_user_id = create_user_id == null ? null : create_user_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_user.update_date
     *
     * @return the value of ujn_user.update_date
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public Date getUpdate_date() {
        return update_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_user.update_date
     *
     * @param update_date the value for ujn_user.update_date
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public void setUpdate_date(Date update_date) {
        this.update_date = update_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_user.update_user_id
     *
     * @return the value of ujn_user.update_user_id
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public String getUpdate_user_id() {
        return update_user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_user.update_user_id
     *
     * @param update_user_id the value for ujn_user.update_user_id
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public void setUpdate_user_id(String update_user_id) {
        this.update_user_id = update_user_id == null ? null : update_user_id.trim();
    }

	public String getDept() {
		return dept;
	}

	public void setDept(String dept) {
		this.dept = dept;
	}

	public String getStatus_name() {
		return status_name;
	}

	public void setStatus_name(String status_name) {
		this.status_name = status_name;
	}
}