package framework.system.model;

public class UserRole {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_user_role.Id
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_user_role.user_code
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    private String user_code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_user_role.role_code
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    private String role_code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_user_role.status
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_user_role.Id
     *
     * @return the value of ujn_user_role.Id
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_user_role.Id
     *
     * @param id the value for ujn_user_role.Id
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_user_role.user_code
     *
     * @return the value of ujn_user_role.user_code
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public String getUser_code() {
        return user_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_user_role.user_code
     *
     * @param user_code the value for ujn_user_role.user_code
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public void setUser_code(String user_code) {
        this.user_code = user_code == null ? null : user_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_user_role.role_code
     *
     * @return the value of ujn_user_role.role_code
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public String getRole_code() {
        return role_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_user_role.role_code
     *
     * @param role_code the value for ujn_user_role.role_code
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public void setRole_code(String role_code) {
        this.role_code = role_code == null ? null : role_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_user_role.status
     *
     * @return the value of ujn_user_role.status
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_user_role.status
     *
     * @param status the value for ujn_user_role.status
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
}