package framework.system.model;

import java.util.Date;

public class UserDept {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_user_dept.Id
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_user_dept.user_id
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    private String user_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_user_dept.dept_code
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    private String dept_code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_user_dept.create_date
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    private Date create_date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_user_dept.create_user_id
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    private String create_user_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_user_dept.update_date
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    private String update_date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_user_dept.update_user_id
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    private String update_user_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_user_dept.remark
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_user_dept.Id
     *
     * @return the value of ujn_user_dept.Id
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_user_dept.Id
     *
     * @param id the value for ujn_user_dept.Id
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_user_dept.user_id
     *
     * @return the value of ujn_user_dept.user_id
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public String getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_user_dept.user_id
     *
     * @param user_id the value for ujn_user_dept.user_id
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public void setUser_id(String user_id) {
        this.user_id = user_id == null ? null : user_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_user_dept.dept_code
     *
     * @return the value of ujn_user_dept.dept_code
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public String getDept_code() {
        return dept_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_user_dept.dept_code
     *
     * @param dept_code the value for ujn_user_dept.dept_code
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public void setDept_code(String dept_code) {
        this.dept_code = dept_code == null ? null : dept_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_user_dept.create_date
     *
     * @return the value of ujn_user_dept.create_date
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public Date getCreate_date() {
        return create_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_user_dept.create_date
     *
     * @param create_date the value for ujn_user_dept.create_date
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public void setCreate_date(Date create_date) {
        this.create_date = create_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_user_dept.create_user_id
     *
     * @return the value of ujn_user_dept.create_user_id
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public String getCreate_user_id() {
        return create_user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_user_dept.create_user_id
     *
     * @param create_user_id the value for ujn_user_dept.create_user_id
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public void setCreate_user_id(String create_user_id) {
        this.create_user_id = create_user_id == null ? null : create_user_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_user_dept.update_date
     *
     * @return the value of ujn_user_dept.update_date
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public String getUpdate_date() {
        return update_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_user_dept.update_date
     *
     * @param update_date the value for ujn_user_dept.update_date
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public void setUpdate_date(String update_date) {
        this.update_date = update_date == null ? null : update_date.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_user_dept.update_user_id
     *
     * @return the value of ujn_user_dept.update_user_id
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public String getUpdate_user_id() {
        return update_user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_user_dept.update_user_id
     *
     * @param update_user_id the value for ujn_user_dept.update_user_id
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public void setUpdate_user_id(String update_user_id) {
        this.update_user_id = update_user_id == null ? null : update_user_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_user_dept.remark
     *
     * @return the value of ujn_user_dept.remark
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_user_dept.remark
     *
     * @param remark the value for ujn_user_dept.remark
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}