package framework.system.model;

public class UserCollect {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_user_collect.Id
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_user_collect.user_code
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    private String user_code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_user_collect.funcright_code
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    private String funcright_code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_user_collect.status
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_user_collect.Id
     *
     * @return the value of ujn_user_collect.Id
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_user_collect.Id
     *
     * @param id the value for ujn_user_collect.Id
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_user_collect.user_code
     *
     * @return the value of ujn_user_collect.user_code
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public String getUser_code() {
        return user_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_user_collect.user_code
     *
     * @param user_code the value for ujn_user_collect.user_code
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public void setUser_code(String user_code) {
        this.user_code = user_code == null ? null : user_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_user_collect.funcright_code
     *
     * @return the value of ujn_user_collect.funcright_code
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public String getFuncright_code() {
        return funcright_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_user_collect.funcright_code
     *
     * @param funcright_code the value for ujn_user_collect.funcright_code
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public void setFuncright_code(String funcright_code) {
        this.funcright_code = funcright_code == null ? null : funcright_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_user_collect.status
     *
     * @return the value of ujn_user_collect.status
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_user_collect.status
     *
     * @param status the value for ujn_user_collect.status
     *
     * @mbg.generated Wed Jan 18 11:12:08 CST 2017
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
}