package com.yuanyuansinian.model.cemetery;

public class CemeteryWithBLOBs extends Cemetery {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_cemetery.img_index
     *
     * @mbg.generated Fri Mar 10 16:23:57 CST 2017
     */
    private byte[] img_index;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_cemetery.content
     *
     * @mbg.generated Fri Mar 10 16:23:57 CST 2017
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_cemetery.img_index
     *
     * @return the value of ujn_cemetery.img_index
     *
     * @mbg.generated Fri Mar 10 16:23:57 CST 2017
     */
    public byte[] getImg_index() {
        return img_index;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_cemetery.img_index
     *
     * @param img_index the value for ujn_cemetery.img_index
     *
     * @mbg.generated Fri Mar 10 16:23:57 CST 2017
     */
    public void setImg_index(byte[] img_index) {
        this.img_index = img_index;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_cemetery.content
     *
     * @return the value of ujn_cemetery.content
     *
     * @mbg.generated Fri Mar 10 16:23:57 CST 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_cemetery.content
     *
     * @param content the value for ujn_cemetery.content
     *
     * @mbg.generated Fri Mar 10 16:23:57 CST 2017
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}