package com.yuanyuansinian.dao.member;

import java.util.List;
import java.util.Map;

import com.yuanyuansinian.model.member.Member;

public interface MemberMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujn_member
     *
     * @mbg.generated Tue Mar 07 22:57:46 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujn_member
     *
     * @mbg.generated Tue Mar 07 22:57:46 CST 2017
     */
    int insert(Member record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujn_member
     *
     * @mbg.generated Tue Mar 07 22:57:46 CST 2017
     */
    int insertSelective(Member record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujn_member
     *
     * @mbg.generated Tue Mar 07 22:57:46 CST 2017
     */
    Member selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujn_member
     *
     * @mbg.generated Tue Mar 07 22:57:46 CST 2017
     */
    int updateByPrimaryKeySelective(Member record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujn_member
     *
     * @mbg.generated Tue Mar 07 22:57:46 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(Member record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujn_member
     *
     * @mbg.generated Tue Mar 07 22:57:46 CST 2017
     */
    int updateByPrimaryKey(Member record);

	List<Member> queryMemberList(Member member);

	Member queryMemberByPhone(Map<String, Object> map);

	int queryMemberCountByPhone(String phone);

	int queryMemberCountByEmail(String email);

	Member queryMemberByEmail(Map<String, Object> map);

	void uploadImg(Member member);
}