package com.yuanyuansinian.model.warehouse;

public class Warehouse {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_warehouse.Id
     *
     * @mbg.generated Fri May 12 17:35:29 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_warehouse.order_id
     *
     * @mbg.generated Fri May 12 17:35:29 CST 2017
     */
    private String order_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_warehouse.member_id
     *
     * @mbg.generated Fri May 12 17:35:29 CST 2017
     */
    private String member_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_warehouse.product_id
     *
     * @mbg.generated Fri May 12 17:35:29 CST 2017
     */
    private String product_id;
    private String product_name;
    private String product_img;
    private String price_site;
    private String hall_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_warehouse.purchase_date
     *
     * @mbg.generated Fri May 12 17:35:29 CST 2017
     */
    private String purchase_date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_warehouse.use_date
     *
     * @mbg.generated Fri May 12 17:35:29 CST 2017
     */
    private String use_date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_warehouse.validity_day
     *
     * @mbg.generated Fri May 12 17:35:29 CST 2017
     */
    private String validity_day;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_warehouse.end_date
     *
     * @mbg.generated Fri May 12 17:35:29 CST 2017
     */
    private String end_date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_warehouse.use_status
     *
     * @mbg.generated Fri May 12 17:35:29 CST 2017
     */
    private String use_status;
    private String use_status_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_warehouse.use_flag
     *
     * @mbg.generated Fri May 12 17:35:29 CST 2017
     */
    private String use_flag;
    
    private String product_type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_warehouse.Id
     *
     * @return the value of ujn_warehouse.Id
     *
     * @mbg.generated Fri May 12 17:35:29 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_warehouse.Id
     *
     * @param id the value for ujn_warehouse.Id
     *
     * @mbg.generated Fri May 12 17:35:29 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_warehouse.order_id
     *
     * @return the value of ujn_warehouse.order_id
     *
     * @mbg.generated Fri May 12 17:35:29 CST 2017
     */
    public String getOrder_id() {
        return order_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_warehouse.order_id
     *
     * @param order_id the value for ujn_warehouse.order_id
     *
     * @mbg.generated Fri May 12 17:35:29 CST 2017
     */
    public void setOrder_id(String order_id) {
        this.order_id = order_id == null ? null : order_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_warehouse.member_id
     *
     * @return the value of ujn_warehouse.member_id
     *
     * @mbg.generated Fri May 12 17:35:29 CST 2017
     */
    public String getMember_id() {
        return member_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_warehouse.member_id
     *
     * @param member_id the value for ujn_warehouse.member_id
     *
     * @mbg.generated Fri May 12 17:35:29 CST 2017
     */
    public void setMember_id(String member_id) {
        this.member_id = member_id == null ? null : member_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_warehouse.product_id
     *
     * @return the value of ujn_warehouse.product_id
     *
     * @mbg.generated Fri May 12 17:35:29 CST 2017
     */
    public String getProduct_id() {
        return product_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_warehouse.product_id
     *
     * @param product_id the value for ujn_warehouse.product_id
     *
     * @mbg.generated Fri May 12 17:35:29 CST 2017
     */
    public void setProduct_id(String product_id) {
        this.product_id = product_id == null ? null : product_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_warehouse.purchase_date
     *
     * @return the value of ujn_warehouse.purchase_date
     *
     * @mbg.generated Fri May 12 17:35:29 CST 2017
     */
    public String getPurchase_date() {
        return purchase_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_warehouse.purchase_date
     *
     * @param purchase_date the value for ujn_warehouse.purchase_date
     *
     * @mbg.generated Fri May 12 17:35:29 CST 2017
     */
    public void setPurchase_date(String purchase_date) {
        this.purchase_date = purchase_date == null ? null : purchase_date.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_warehouse.use_date
     *
     * @return the value of ujn_warehouse.use_date
     *
     * @mbg.generated Fri May 12 17:35:29 CST 2017
     */
    public String getUse_date() {
        return use_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_warehouse.use_date
     *
     * @param use_date the value for ujn_warehouse.use_date
     *
     * @mbg.generated Fri May 12 17:35:29 CST 2017
     */
    public void setUse_date(String use_date) {
        this.use_date = use_date == null ? null : use_date.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_warehouse.validity_day
     *
     * @return the value of ujn_warehouse.validity_day
     *
     * @mbg.generated Fri May 12 17:35:29 CST 2017
     */
    public String getValidity_day() {
        return validity_day;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_warehouse.validity_day
     *
     * @param validity_day the value for ujn_warehouse.validity_day
     *
     * @mbg.generated Fri May 12 17:35:29 CST 2017
     */
    public void setValidity_day(String validity_day) {
        this.validity_day = validity_day == null ? null : validity_day.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_warehouse.end_date
     *
     * @return the value of ujn_warehouse.end_date
     *
     * @mbg.generated Fri May 12 17:35:29 CST 2017
     */
    public String getEnd_date() {
        return end_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_warehouse.end_date
     *
     * @param end_date the value for ujn_warehouse.end_date
     *
     * @mbg.generated Fri May 12 17:35:29 CST 2017
     */
    public void setEnd_date(String end_date) {
        this.end_date = end_date == null ? null : end_date.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_warehouse.use_status
     *
     * @return the value of ujn_warehouse.use_status
     *
     * @mbg.generated Fri May 12 17:35:29 CST 2017
     */
    public String getUse_status() {
        return use_status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_warehouse.use_status
     *
     * @param use_status the value for ujn_warehouse.use_status
     *
     * @mbg.generated Fri May 12 17:35:29 CST 2017
     */
    public void setUse_status(String use_status) {
        this.use_status = use_status == null ? null : use_status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_warehouse.use_flag
     *
     * @return the value of ujn_warehouse.use_flag
     *
     * @mbg.generated Fri May 12 17:35:29 CST 2017
     */
    public String getUse_flag() {
        return use_flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_warehouse.use_flag
     *
     * @param use_flag the value for ujn_warehouse.use_flag
     *
     * @mbg.generated Fri May 12 17:35:29 CST 2017
     */
    public void setUse_flag(String use_flag) {
        this.use_flag = use_flag == null ? null : use_flag.trim();
    }

	public String getProduct_type() {
		return product_type;
	}

	public void setProduct_type(String product_type) {
		this.product_type = product_type;
	}

	public String getProduct_name() {
		return product_name;
	}

	public void setProduct_name(String product_name) {
		this.product_name = product_name;
	}

	public String getProduct_img() {
		return product_img;
	}

	public void setProduct_img(String product_img) {
		this.product_img = product_img;
	}

	public String getHall_id() {
		return hall_id;
	}

	public void setHall_id(String hall_id) {
		this.hall_id = hall_id;
	}

	public String getPrice_site() {
		return price_site;
	}

	public void setPrice_site(String price_site) {
		this.price_site = price_site;
	}

	public String getUse_status_name() {
		return use_status_name;
	}

	public void setUse_status_name(String use_status_name) {
		this.use_status_name = use_status_name;
	}
}