package ujn.school.cn.model.apply;

public class Apply {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_apply.Id
     *
     * @mbg.generated Tue Apr 11 16:37:35 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_apply.user_name
     *
     * @mbg.generated Tue Apr 11 16:37:35 CST 2017
     */
    private String user_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_apply.user_unit
     *
     * @mbg.generated Tue Apr 11 16:37:35 CST 2017
     */
    private String user_unit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_apply.user_tel
     *
     * @mbg.generated Tue Apr 11 16:37:35 CST 2017
     */
    private String user_tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_apply.address
     *
     * @mbg.generated Tue Apr 11 16:37:35 CST 2017
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_apply.postcode
     *
     * @mbg.generated Tue Apr 11 16:37:35 CST 2017
     */
    private String postcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_apply.id_type
     *
     * @mbg.generated Tue Apr 11 16:37:35 CST 2017
     */
    private String id_type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_apply.id_num
     *
     * @mbg.generated Tue Apr 11 16:37:35 CST 2017
     */
    private String id_num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_apply.id_file
     *
     * @mbg.generated Tue Apr 11 16:37:35 CST 2017
     */
    private String id_file;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_apply.content
     *
     * @mbg.generated Tue Apr 11 16:37:35 CST 2017
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_apply.reason
     *
     * @mbg.generated Tue Apr 11 16:37:35 CST 2017
     */
    private String reason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_apply.open_type
     *
     * @mbg.generated Tue Apr 11 16:37:35 CST 2017
     */
    private String open_type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_apply.remark
     *
     * @mbg.generated Tue Apr 11 16:37:35 CST 2017
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_apply.check_pwd
     *
     * @mbg.generated Tue Apr 11 16:37:35 CST 2017
     */
    private String check_pwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_apply.user_type
     *
     * @mbg.generated Tue Apr 11 16:37:35 CST 2017
     */
    private String user_type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_apply.create_date
     *
     * @mbg.generated Tue Apr 11 16:37:35 CST 2017
     */
    private String create_date;
    
    private String credit_code;
    private String credit_code_file;
    private String apply_file;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_apply.Id
     *
     * @return the value of ujn_apply.Id
     *
     * @mbg.generated Tue Apr 11 16:37:35 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_apply.Id
     *
     * @param id the value for ujn_apply.Id
     *
     * @mbg.generated Tue Apr 11 16:37:35 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_apply.user_name
     *
     * @return the value of ujn_apply.user_name
     *
     * @mbg.generated Tue Apr 11 16:37:35 CST 2017
     */
    public String getUser_name() {
        return user_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_apply.user_name
     *
     * @param user_name the value for ujn_apply.user_name
     *
     * @mbg.generated Tue Apr 11 16:37:35 CST 2017
     */
    public void setUser_name(String user_name) {
        this.user_name = user_name == null ? null : user_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_apply.user_unit
     *
     * @return the value of ujn_apply.user_unit
     *
     * @mbg.generated Tue Apr 11 16:37:35 CST 2017
     */
    public String getUser_unit() {
        return user_unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_apply.user_unit
     *
     * @param user_unit the value for ujn_apply.user_unit
     *
     * @mbg.generated Tue Apr 11 16:37:35 CST 2017
     */
    public void setUser_unit(String user_unit) {
        this.user_unit = user_unit == null ? null : user_unit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_apply.user_tel
     *
     * @return the value of ujn_apply.user_tel
     *
     * @mbg.generated Tue Apr 11 16:37:35 CST 2017
     */
    public String getUser_tel() {
        return user_tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_apply.user_tel
     *
     * @param user_tel the value for ujn_apply.user_tel
     *
     * @mbg.generated Tue Apr 11 16:37:35 CST 2017
     */
    public void setUser_tel(String user_tel) {
        this.user_tel = user_tel == null ? null : user_tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_apply.address
     *
     * @return the value of ujn_apply.address
     *
     * @mbg.generated Tue Apr 11 16:37:35 CST 2017
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_apply.address
     *
     * @param address the value for ujn_apply.address
     *
     * @mbg.generated Tue Apr 11 16:37:35 CST 2017
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_apply.postcode
     *
     * @return the value of ujn_apply.postcode
     *
     * @mbg.generated Tue Apr 11 16:37:35 CST 2017
     */
    public String getPostcode() {
        return postcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_apply.postcode
     *
     * @param postcode the value for ujn_apply.postcode
     *
     * @mbg.generated Tue Apr 11 16:37:35 CST 2017
     */
    public void setPostcode(String postcode) {
        this.postcode = postcode == null ? null : postcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_apply.id_type
     *
     * @return the value of ujn_apply.id_type
     *
     * @mbg.generated Tue Apr 11 16:37:35 CST 2017
     */
    public String getId_type() {
        return id_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_apply.id_type
     *
     * @param id_type the value for ujn_apply.id_type
     *
     * @mbg.generated Tue Apr 11 16:37:35 CST 2017
     */
    public void setId_type(String id_type) {
        this.id_type = id_type == null ? null : id_type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_apply.id_num
     *
     * @return the value of ujn_apply.id_num
     *
     * @mbg.generated Tue Apr 11 16:37:35 CST 2017
     */
    public String getId_num() {
        return id_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_apply.id_num
     *
     * @param id_num the value for ujn_apply.id_num
     *
     * @mbg.generated Tue Apr 11 16:37:35 CST 2017
     */
    public void setId_num(String id_num) {
        this.id_num = id_num == null ? null : id_num.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_apply.id_file
     *
     * @return the value of ujn_apply.id_file
     *
     * @mbg.generated Tue Apr 11 16:37:35 CST 2017
     */
    public String getId_file() {
        return id_file;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_apply.id_file
     *
     * @param id_file the value for ujn_apply.id_file
     *
     * @mbg.generated Tue Apr 11 16:37:35 CST 2017
     */
    public void setId_file(String id_file) {
        this.id_file = id_file == null ? null : id_file.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_apply.content
     *
     * @return the value of ujn_apply.content
     *
     * @mbg.generated Tue Apr 11 16:37:35 CST 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_apply.content
     *
     * @param content the value for ujn_apply.content
     *
     * @mbg.generated Tue Apr 11 16:37:35 CST 2017
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_apply.reason
     *
     * @return the value of ujn_apply.reason
     *
     * @mbg.generated Tue Apr 11 16:37:35 CST 2017
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_apply.reason
     *
     * @param reason the value for ujn_apply.reason
     *
     * @mbg.generated Tue Apr 11 16:37:35 CST 2017
     */
    public void setReason(String reason) {
        this.reason = reason == null ? null : reason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_apply.open_type
     *
     * @return the value of ujn_apply.open_type
     *
     * @mbg.generated Tue Apr 11 16:37:35 CST 2017
     */
    public String getOpen_type() {
        return open_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_apply.open_type
     *
     * @param open_type the value for ujn_apply.open_type
     *
     * @mbg.generated Tue Apr 11 16:37:35 CST 2017
     */
    public void setOpen_type(String open_type) {
        this.open_type = open_type == null ? null : open_type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_apply.remark
     *
     * @return the value of ujn_apply.remark
     *
     * @mbg.generated Tue Apr 11 16:37:35 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_apply.remark
     *
     * @param remark the value for ujn_apply.remark
     *
     * @mbg.generated Tue Apr 11 16:37:35 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_apply.check_pwd
     *
     * @return the value of ujn_apply.check_pwd
     *
     * @mbg.generated Tue Apr 11 16:37:35 CST 2017
     */
    public String getCheck_pwd() {
        return check_pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_apply.check_pwd
     *
     * @param check_pwd the value for ujn_apply.check_pwd
     *
     * @mbg.generated Tue Apr 11 16:37:35 CST 2017
     */
    public void setCheck_pwd(String check_pwd) {
        this.check_pwd = check_pwd == null ? null : check_pwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_apply.user_type
     *
     * @return the value of ujn_apply.user_type
     *
     * @mbg.generated Tue Apr 11 16:37:35 CST 2017
     */
    public String getUser_type() {
        return user_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_apply.user_type
     *
     * @param user_type the value for ujn_apply.user_type
     *
     * @mbg.generated Tue Apr 11 16:37:35 CST 2017
     */
    public void setUser_type(String user_type) {
        this.user_type = user_type == null ? null : user_type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_apply.create_date
     *
     * @return the value of ujn_apply.create_date
     *
     * @mbg.generated Tue Apr 11 16:37:35 CST 2017
     */
    public String getCreate_date() {
        return create_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_apply.create_date
     *
     * @param create_date the value for ujn_apply.create_date
     *
     * @mbg.generated Tue Apr 11 16:37:35 CST 2017
     */
    public void setCreate_date(String create_date) {
        this.create_date = create_date == null ? null : create_date.trim();
    }

	public String getCredit_code() {
		return credit_code;
	}

	public void setCredit_code(String credit_code) {
		this.credit_code = credit_code;
	}

	public String getCredit_code_file() {
		return credit_code_file;
	}

	public void setCredit_code_file(String credit_code_file) {
		this.credit_code_file = credit_code_file;
	}

	public String getApply_file() {
		return apply_file;
	}

	public void setApply_file(String apply_file) {
		this.apply_file = apply_file;
	}
}