package com.yuanyuansinian.dao.oration;

import java.util.List;
import java.util.Map;

import com.yuanyuansinian.model.oration.Oration;

public interface OrationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujn_oration
     *
     * @mbg.generated Fri Mar 10 10:06:41 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujn_oration
     *
     * @mbg.generated Fri Mar 10 10:06:41 CST 2017
     */
    int insert(Oration record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujn_oration
     *
     * @mbg.generated Fri Mar 10 10:06:41 CST 2017
     */
    int insertSelective(Oration record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujn_oration
     *
     * @mbg.generated Fri Mar 10 10:06:41 CST 2017
     */
    Oration selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujn_oration
     *
     * @mbg.generated Fri Mar 10 10:06:41 CST 2017
     */
    int updateByPrimaryKeySelective(Oration record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujn_oration
     *
     * @mbg.generated Fri Mar 10 10:06:41 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(Oration record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujn_oration
     *
     * @mbg.generated Fri Mar 10 10:06:41 CST 2017
     */
    int updateByPrimaryKey(Oration record);

	List<Oration> queryOrationList(Oration hall);

	List<Oration> queryOrationListByOpenType(Oration hall);

	List<Oration> queryOrationListByMember(Map<String, Object> map);

	List<Oration> queryOrationListByType(Oration hall);

	List<Oration> queryOrationPageListByMember(Oration oration);

	List<Oration> queryOrationNewList(int countNum);
}