package ujn.school.cn.dao.carousel;

import java.util.List;

import ujn.school.cn.model.carousel.Carousel;

public interface CarouselMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujn_carousel
     *
     * @mbg.generated Wed Mar 22 22:22:00 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujn_carousel
     *
     * @mbg.generated Wed Mar 22 22:22:00 CST 2017
     */
    int insert(Carousel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujn_carousel
     *
     * @mbg.generated Wed Mar 22 22:22:00 CST 2017
     */
    int insertSelective(Carousel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujn_carousel
     *
     * @mbg.generated Wed Mar 22 22:22:00 CST 2017
     */
    Carousel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujn_carousel
     *
     * @mbg.generated Wed Mar 22 22:22:00 CST 2017
     */
    int updateByPrimaryKeySelective(Carousel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujn_carousel
     *
     * @mbg.generated Wed Mar 22 22:22:00 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(Carousel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujn_carousel
     *
     * @mbg.generated Wed Mar 22 22:22:00 CST 2017
     */
    int updateByPrimaryKey(Carousel record);

	List<Carousel> queryCarouselList(Carousel carousel);

	void uploadCarouselImg(Carousel carousel);

	List<Carousel> queryCarouselBySingle();
}