package com.yuanyuansinian.dao.cemetery;

import com.yuanyuansinian.model.cemetery.Cemetery;
import com.yuanyuansinian.model.cemetery.CemeteryWithBLOBs;

public interface CemeteryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujn_cemetery
     *
     * @mbg.generated Fri Mar 10 16:23:57 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujn_cemetery
     *
     * @mbg.generated Fri Mar 10 16:23:57 CST 2017
     */
    int insert(CemeteryWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujn_cemetery
     *
     * @mbg.generated Fri Mar 10 16:23:57 CST 2017
     */
    int insertSelective(CemeteryWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujn_cemetery
     *
     * @mbg.generated Fri Mar 10 16:23:57 CST 2017
     */
    CemeteryWithBLOBs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujn_cemetery
     *
     * @mbg.generated Fri Mar 10 16:23:57 CST 2017
     */
    int updateByPrimaryKeySelective(CemeteryWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujn_cemetery
     *
     * @mbg.generated Fri Mar 10 16:23:57 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(CemeteryWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujn_cemetery
     *
     * @mbg.generated Fri Mar 10 16:23:57 CST 2017
     */
    int updateByPrimaryKey(Cemetery record);
}