package com.suncity.model.carousel;

public class Carousel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_carousel.Id
     *
     * @mbg.generated Wed Mar 22 22:22:00 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_carousel.title
     *
     * @mbg.generated Wed Mar 22 22:22:00 CST 2017
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_carousel.description
     *
     * @mbg.generated Wed Mar 22 22:22:00 CST 2017
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_carousel.img_url
     *
     * @mbg.generated Wed Mar 22 22:22:00 CST 2017
     */
    private String img_url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_carousel.no_order
     *
     * @mbg.generated Wed Mar 22 22:22:00 CST 2017
     */
    private Integer no_order;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_carousel.remark
     *
     * @mbg.generated Wed Mar 22 22:22:00 CST 2017
     */
    private String remark;
    
    private String carousel_type;
    private String carousel_type_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_carousel.img
     *
     * @mbg.generated Wed Mar 22 22:22:00 CST 2017
     */
    private byte[] img;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_carousel.Id
     *
     * @return the value of ujn_carousel.Id
     *
     * @mbg.generated Wed Mar 22 22:22:00 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_carousel.Id
     *
     * @param id the value for ujn_carousel.Id
     *
     * @mbg.generated Wed Mar 22 22:22:00 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_carousel.title
     *
     * @return the value of ujn_carousel.title
     *
     * @mbg.generated Wed Mar 22 22:22:00 CST 2017
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_carousel.title
     *
     * @param title the value for ujn_carousel.title
     *
     * @mbg.generated Wed Mar 22 22:22:00 CST 2017
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_carousel.description
     *
     * @return the value of ujn_carousel.description
     *
     * @mbg.generated Wed Mar 22 22:22:00 CST 2017
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_carousel.description
     *
     * @param description the value for ujn_carousel.description
     *
     * @mbg.generated Wed Mar 22 22:22:00 CST 2017
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_carousel.img_url
     *
     * @return the value of ujn_carousel.img_url
     *
     * @mbg.generated Wed Mar 22 22:22:00 CST 2017
     */
    public String getImg_url() {
        return img_url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_carousel.img_url
     *
     * @param img_url the value for ujn_carousel.img_url
     *
     * @mbg.generated Wed Mar 22 22:22:00 CST 2017
     */
    public void setImg_url(String img_url) {
        this.img_url = img_url == null ? null : img_url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_carousel.no_order
     *
     * @return the value of ujn_carousel.no_order
     *
     * @mbg.generated Wed Mar 22 22:22:00 CST 2017
     */
    public Integer getNo_order() {
        return no_order;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_carousel.no_order
     *
     * @param no_order the value for ujn_carousel.no_order
     *
     * @mbg.generated Wed Mar 22 22:22:00 CST 2017
     */
    public void setNo_order(Integer no_order) {
        this.no_order = no_order;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_carousel.remark
     *
     * @return the value of ujn_carousel.remark
     *
     * @mbg.generated Wed Mar 22 22:22:00 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_carousel.remark
     *
     * @param remark the value for ujn_carousel.remark
     *
     * @mbg.generated Wed Mar 22 22:22:00 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_carousel.img
     *
     * @return the value of ujn_carousel.img
     *
     * @mbg.generated Wed Mar 22 22:22:00 CST 2017
     */
    public byte[] getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_carousel.img
     *
     * @param img the value for ujn_carousel.img
     *
     * @mbg.generated Wed Mar 22 22:22:00 CST 2017
     */
    public void setImg(byte[] img) {
        this.img = img;
    }

	public String getCarousel_type() {
		return carousel_type;
	}

	public void setCarousel_type(String carousel_type) {
		this.carousel_type = carousel_type;
	}

	public String getCarousel_type_name() {
		return carousel_type_name;
	}

	public void setCarousel_type_name(String carousel_type_name) {
		this.carousel_type_name = carousel_type_name;
	}
}