package ujn.school.cn.model.config;

public class Config {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_site_config.Id
     *
     * @mbg.generated Mon Apr 10 13:49:23 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_site_config.name
     *
     * @mbg.generated Mon Apr 10 13:49:23 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_site_config.keywords
     *
     * @mbg.generated Mon Apr 10 13:49:23 CST 2017
     */
    private String keywords;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_site_config.description
     *
     * @mbg.generated Mon Apr 10 13:49:23 CST 2017
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_site_config.file_path
     *
     * @mbg.generated Mon Apr 10 13:49:23 CST 2017
     */
    private String file_path;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_site_config.copyright
     *
     * @mbg.generated Mon Apr 10 13:49:23 CST 2017
     */
    private String copyright;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_site_config.record_num
     *
     * @mbg.generated Mon Apr 10 13:49:23 CST 2017
     */
    private String record_num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_site_config.statistical_code
     *
     * @mbg.generated Mon Apr 10 13:49:23 CST 2017
     */
    private String statistical_code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_site_config.default_pwd
     *
     * @mbg.generated Mon Apr 10 13:49:23 CST 2017
     */
    private String default_pwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_site_config.ip_section
     *
     * @mbg.generated Mon Apr 10 13:49:23 CST 2017
     */
    private String ip_section;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_site_config.login_count
     *
     * @mbg.generated Mon Apr 10 13:49:23 CST 2017
     */
    private String login_count;
    
    private int count;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_site_config.Id
     *
     * @return the value of ujn_site_config.Id
     *
     * @mbg.generated Mon Apr 10 13:49:23 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_site_config.Id
     *
     * @param id the value for ujn_site_config.Id
     *
     * @mbg.generated Mon Apr 10 13:49:23 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_site_config.name
     *
     * @return the value of ujn_site_config.name
     *
     * @mbg.generated Mon Apr 10 13:49:23 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_site_config.name
     *
     * @param name the value for ujn_site_config.name
     *
     * @mbg.generated Mon Apr 10 13:49:23 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_site_config.keywords
     *
     * @return the value of ujn_site_config.keywords
     *
     * @mbg.generated Mon Apr 10 13:49:23 CST 2017
     */
    public String getKeywords() {
        return keywords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_site_config.keywords
     *
     * @param keywords the value for ujn_site_config.keywords
     *
     * @mbg.generated Mon Apr 10 13:49:23 CST 2017
     */
    public void setKeywords(String keywords) {
        this.keywords = keywords == null ? null : keywords.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_site_config.description
     *
     * @return the value of ujn_site_config.description
     *
     * @mbg.generated Mon Apr 10 13:49:23 CST 2017
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_site_config.description
     *
     * @param description the value for ujn_site_config.description
     *
     * @mbg.generated Mon Apr 10 13:49:23 CST 2017
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_site_config.file_path
     *
     * @return the value of ujn_site_config.file_path
     *
     * @mbg.generated Mon Apr 10 13:49:23 CST 2017
     */
    public String getFile_path() {
        return file_path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_site_config.file_path
     *
     * @param file_path the value for ujn_site_config.file_path
     *
     * @mbg.generated Mon Apr 10 13:49:23 CST 2017
     */
    public void setFile_path(String file_path) {
        this.file_path = file_path == null ? null : file_path.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_site_config.copyright
     *
     * @return the value of ujn_site_config.copyright
     *
     * @mbg.generated Mon Apr 10 13:49:23 CST 2017
     */
    public String getCopyright() {
        return copyright;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_site_config.copyright
     *
     * @param copyright the value for ujn_site_config.copyright
     *
     * @mbg.generated Mon Apr 10 13:49:23 CST 2017
     */
    public void setCopyright(String copyright) {
        this.copyright = copyright == null ? null : copyright.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_site_config.record_num
     *
     * @return the value of ujn_site_config.record_num
     *
     * @mbg.generated Mon Apr 10 13:49:23 CST 2017
     */
    public String getRecord_num() {
        return record_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_site_config.record_num
     *
     * @param record_num the value for ujn_site_config.record_num
     *
     * @mbg.generated Mon Apr 10 13:49:23 CST 2017
     */
    public void setRecord_num(String record_num) {
        this.record_num = record_num == null ? null : record_num.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_site_config.statistical_code
     *
     * @return the value of ujn_site_config.statistical_code
     *
     * @mbg.generated Mon Apr 10 13:49:23 CST 2017
     */
    public String getStatistical_code() {
        return statistical_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_site_config.statistical_code
     *
     * @param statistical_code the value for ujn_site_config.statistical_code
     *
     * @mbg.generated Mon Apr 10 13:49:23 CST 2017
     */
    public void setStatistical_code(String statistical_code) {
        this.statistical_code = statistical_code == null ? null : statistical_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_site_config.default_pwd
     *
     * @return the value of ujn_site_config.default_pwd
     *
     * @mbg.generated Mon Apr 10 13:49:23 CST 2017
     */
    public String getDefault_pwd() {
        return default_pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_site_config.default_pwd
     *
     * @param default_pwd the value for ujn_site_config.default_pwd
     *
     * @mbg.generated Mon Apr 10 13:49:23 CST 2017
     */
    public void setDefault_pwd(String default_pwd) {
        this.default_pwd = default_pwd == null ? null : default_pwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_site_config.ip_section
     *
     * @return the value of ujn_site_config.ip_section
     *
     * @mbg.generated Mon Apr 10 13:49:23 CST 2017
     */
    public String getIp_section() {
        return ip_section;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_site_config.ip_section
     *
     * @param ip_section the value for ujn_site_config.ip_section
     *
     * @mbg.generated Mon Apr 10 13:49:23 CST 2017
     */
    public void setIp_section(String ip_section) {
        this.ip_section = ip_section == null ? null : ip_section.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_site_config.login_count
     *
     * @return the value of ujn_site_config.login_count
     *
     * @mbg.generated Mon Apr 10 13:49:23 CST 2017
     */
    public String getLogin_count() {
        return login_count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_site_config.login_count
     *
     * @param login_count the value for ujn_site_config.login_count
     *
     * @mbg.generated Mon Apr 10 13:49:23 CST 2017
     */
    public void setLogin_count(String login_count) {
        this.login_count = login_count == null ? null : login_count.trim();
    }

	public int getCount() {
		return count;
	}

	public void setCount(int count) {
		this.count = count;
	}
}