package ujn.school.cn.dao.apply;

import java.util.List;

import ujn.school.cn.model.apply.Apply;

public interface ApplyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujn_apply
     *
     * @mbg.generated Tue Apr 11 16:37:36 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujn_apply
     *
     * @mbg.generated Tue Apr 11 16:37:36 CST 2017
     */
    int insert(Apply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujn_apply
     *
     * @mbg.generated Tue Apr 11 16:37:36 CST 2017
     */
    int insertSelective(Apply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujn_apply
     *
     * @mbg.generated Tue Apr 11 16:37:36 CST 2017
     */
    Apply selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujn_apply
     *
     * @mbg.generated Tue Apr 11 16:37:36 CST 2017
     */
    int updateByPrimaryKeySelective(Apply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujn_apply
     *
     * @mbg.generated Tue Apr 11 16:37:36 CST 2017
     */
    int updateByPrimaryKey(Apply record);

	List<Apply> queryApplyList(Apply apply);

	void uploadIdImg(Apply apply);

	void uploadCreditCodeImg(Apply apply);
}