<script type="text/javascript" src="${pageContext.request.contextPath}/static/js/jquery.min.js"></script>
<script type="text/javascript" src="${pageContext.request.contextPath}/static/hui/admin3.0/static/h-ui/js/H-ui.js"></script> 
<script type="text/javascript" src="${pageContext.request.contextPath}/static/js/layer/layer.js"></script>
<script type="text/javascript" src="${pageContext.request.contextPath}/static/hui/admin3.0/static/h-ui.admin/js/H-ui.admin.js"></script> 
<!-- DataTables -->
<script type="text/javascript" src="${pageContext.request.contextPath}/static/hui/admin3.0/lib/datatables/1.10.0/jquery.dataTables.min.js"></script> 
<!-- 模版 -->
<script type="text/javascript" src="${pageContext.request.contextPath}/static/js/handlebars-v4.0.5.js"></script>
<script type="text/javascript" src="${pageContext.request.contextPath}/static/hui/admin3.0/lib/jquery.contextmenu/jquery.contextmenu.r2.js"></script>