<script type="text/javascript"
	src="${pageContext.request.contextPath}/static/js/jquery.min.js"></script>
<script type="text/javascript"
	src="${pageContext.request.contextPath}/static/js/bootstrap.min.js"></script>
<script type="text/javascript"
	src="${pageContext.request.contextPath}/static/js/layer/layer.js"></script>
<script type="text/javascript"
	src="${pageContext.request.contextPath}/static/js/article.js"></script>
<script type="text/javascript"
	src="${pageContext.request.contextPath}/static/js/nav.js"></script>