package com.suncity.dao.column;

import java.util.List;

import com.suncity.model.column.Column;
import com.suncity.model.column.ColumnWithBLOBs;

public interface ColumnMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujn_column
     *
     * @mbg.generated Mon Feb 06 11:15:53 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujn_column
     *
     * @mbg.generated Mon Feb 06 11:15:53 CST 2017
     */
    int insert(ColumnWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujn_column
     *
     * @mbg.generated Mon Feb 06 11:15:53 CST 2017
     */
    int insertSelective(ColumnWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujn_column
     *
     * @mbg.generated Mon Feb 06 11:15:53 CST 2017
     */
    ColumnWithBLOBs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujn_column
     *
     * @mbg.generated Mon Feb 06 11:15:53 CST 2017
     */
    int updateByPrimaryKeySelective(ColumnWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujn_column
     *
     * @mbg.generated Mon Feb 06 11:15:53 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(ColumnWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujn_column
     *
     * @mbg.generated Mon Feb 06 11:15:53 CST 2017
     */
    int updateByPrimaryKey(Column record);

	List<Column> queryColumnList(Column column);

	List<Column> queryColumnListForNavigation(Integer nav_num);

	List<Column> querySelfAndChildColumnListByColumnId(String columnId);

	List<Column> queryChildColumnListByColumnId(String columnId);

}