package com.suncity.model.member;

public class Member {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_member.Id
     *
     * @mbg.generated Tue Mar 07 22:57:46 CST 2017
     */
    private Integer id;
    
    private Integer days;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_member.login_name
     *
     * @mbg.generated Tue Mar 07 22:57:46 CST 2017
     */
    private String login_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_member.pwd
     *
     * @mbg.generated Tue Mar 07 22:57:46 CST 2017
     */
    private String pwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_member.member_name
     *
     * @mbg.generated Tue Mar 07 22:57:46 CST 2017
     */
    private String member_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_member.real_name
     *
     * @mbg.generated Tue Mar 07 22:57:46 CST 2017
     */
    private String real_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_member.sex
     *
     * @mbg.generated Tue Mar 07 22:57:46 CST 2017
     */
    private String sex;
    private String sex_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_member.phone
     *
     * @mbg.generated Tue Mar 07 22:57:46 CST 2017
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_member.email
     *
     * @mbg.generated Tue Mar 07 22:57:46 CST 2017
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_member.addr_old
     *
     * @mbg.generated Tue Mar 07 22:57:46 CST 2017
     */
    private String addr_old;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_member.addr_now
     *
     * @mbg.generated Tue Mar 07 22:57:46 CST 2017
     */
    private String addr_now;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_member.status
     *
     * @mbg.generated Tue Mar 07 22:57:46 CST 2017
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_member.create_date
     *
     * @mbg.generated Tue Mar 07 22:57:46 CST 2017
     */
    private String create_date;
    
    private Double balance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujn_member.pic
     *
     * @mbg.generated Tue Mar 07 22:57:46 CST 2017
     */
    private byte[] pic;
    
    private String imgs;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_member.Id
     *
     * @return the value of ujn_member.Id
     *
     * @mbg.generated Tue Mar 07 22:57:46 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_member.Id
     *
     * @param id the value for ujn_member.Id
     *
     * @mbg.generated Tue Mar 07 22:57:46 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_member.login_name
     *
     * @return the value of ujn_member.login_name
     *
     * @mbg.generated Tue Mar 07 22:57:46 CST 2017
     */
    public String getLogin_name() {
        return login_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_member.login_name
     *
     * @param login_name the value for ujn_member.login_name
     *
     * @mbg.generated Tue Mar 07 22:57:46 CST 2017
     */
    public void setLogin_name(String login_name) {
        this.login_name = login_name == null ? null : login_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_member.pwd
     *
     * @return the value of ujn_member.pwd
     *
     * @mbg.generated Tue Mar 07 22:57:46 CST 2017
     */
    public String getPwd() {
        return pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_member.pwd
     *
     * @param pwd the value for ujn_member.pwd
     *
     * @mbg.generated Tue Mar 07 22:57:46 CST 2017
     */
    public void setPwd(String pwd) {
        this.pwd = pwd == null ? null : pwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_member.member_name
     *
     * @return the value of ujn_member.member_name
     *
     * @mbg.generated Tue Mar 07 22:57:46 CST 2017
     */
    public String getMember_name() {
        return member_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_member.member_name
     *
     * @param member_name the value for ujn_member.member_name
     *
     * @mbg.generated Tue Mar 07 22:57:46 CST 2017
     */
    public void setMember_name(String member_name) {
        this.member_name = member_name == null ? null : member_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_member.real_name
     *
     * @return the value of ujn_member.real_name
     *
     * @mbg.generated Tue Mar 07 22:57:46 CST 2017
     */
    public String getReal_name() {
        return real_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_member.real_name
     *
     * @param real_name the value for ujn_member.real_name
     *
     * @mbg.generated Tue Mar 07 22:57:46 CST 2017
     */
    public void setReal_name(String real_name) {
        this.real_name = real_name == null ? null : real_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_member.sex
     *
     * @return the value of ujn_member.sex
     *
     * @mbg.generated Tue Mar 07 22:57:46 CST 2017
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_member.sex
     *
     * @param sex the value for ujn_member.sex
     *
     * @mbg.generated Tue Mar 07 22:57:46 CST 2017
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_member.phone
     *
     * @return the value of ujn_member.phone
     *
     * @mbg.generated Tue Mar 07 22:57:46 CST 2017
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_member.phone
     *
     * @param phone the value for ujn_member.phone
     *
     * @mbg.generated Tue Mar 07 22:57:46 CST 2017
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_member.email
     *
     * @return the value of ujn_member.email
     *
     * @mbg.generated Tue Mar 07 22:57:46 CST 2017
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_member.email
     *
     * @param email the value for ujn_member.email
     *
     * @mbg.generated Tue Mar 07 22:57:46 CST 2017
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_member.addr_old
     *
     * @return the value of ujn_member.addr_old
     *
     * @mbg.generated Tue Mar 07 22:57:46 CST 2017
     */
    public String getAddr_old() {
        return addr_old;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_member.addr_old
     *
     * @param addr_old the value for ujn_member.addr_old
     *
     * @mbg.generated Tue Mar 07 22:57:46 CST 2017
     */
    public void setAddr_old(String addr_old) {
        this.addr_old = addr_old == null ? null : addr_old.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_member.addr_now
     *
     * @return the value of ujn_member.addr_now
     *
     * @mbg.generated Tue Mar 07 22:57:46 CST 2017
     */
    public String getAddr_now() {
        return addr_now;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_member.addr_now
     *
     * @param addr_now the value for ujn_member.addr_now
     *
     * @mbg.generated Tue Mar 07 22:57:46 CST 2017
     */
    public void setAddr_now(String addr_now) {
        this.addr_now = addr_now == null ? null : addr_now.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_member.status
     *
     * @return the value of ujn_member.status
     *
     * @mbg.generated Tue Mar 07 22:57:46 CST 2017
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_member.status
     *
     * @param status the value for ujn_member.status
     *
     * @mbg.generated Tue Mar 07 22:57:46 CST 2017
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_member.create_date
     *
     * @return the value of ujn_member.create_date
     *
     * @mbg.generated Tue Mar 07 22:57:46 CST 2017
     */
    public String getCreate_date() {
        return create_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_member.create_date
     *
     * @param create_date the value for ujn_member.create_date
     *
     * @mbg.generated Tue Mar 07 22:57:46 CST 2017
     */
    public void setCreate_date(String create_date) {
        this.create_date = create_date == null ? null : create_date.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujn_member.pic
     *
     * @return the value of ujn_member.pic
     *
     * @mbg.generated Tue Mar 07 22:57:46 CST 2017
     */
    public byte[] getPic() {
        return pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujn_member.pic
     *
     * @param pic the value for ujn_member.pic
     *
     * @mbg.generated Tue Mar 07 22:57:46 CST 2017
     */
    public void setPic(byte[] pic) {
        this.pic = pic;
    }

	public String getSex_name() {
		return sex_name;
	}

	public void setSex_name(String sex_name) {
		this.sex_name = sex_name;
	}

	public Integer getDays() {
		return days;
	}

	public void setDays(Integer days) {
		this.days = days;
	}

	public Double getBalance() {
		return balance;
	}

	public void setBalance(Double balance) {
		this.balance = balance;
	}

	public String getImgs() {
		return imgs;
	}

	public void setImgs(String imgs) {
		this.imgs = imgs;
	}
}